In [ ]:
# =========================================================
# CARI CHANNEL ID YOUTUBE - NICHE HORROR/BRAINROT ANAK
# Untuk dataset skripsi: klasifikasi video viral (XGBoost vs LightGBM)
# =========================================================

# --- 1. INSTALL LIBRARY ---
!pip install google-api-python-client --quiet

# --- 2. IMPORT & SETUP ---
import pandas as pd
import time
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# Masukkan API Key kamu di sini
API_KEY = "(masukkan API KEY kamu di sini)"

youtube = build("youtube", "v3", developerKey=API_KEY)

# --- 3. DAFTAR KEYWORD (CAMPURAN GLOBAL + INDONESIA) ---
# Bisa ditambah/diedit sesuai kebutuhan
KEYWORDS = [
    # GLOBAL (English)
    "sakura school simulator horror story",
    "roblox horror story animation",
    "minecraft horror story scary",
    "horror animation school story",
    "scary animation short story",
    "gta 5 horror story animation",
    "creepy animation horror viral",
    "roblox brainrot horror",
    "minecraft jumpscare horror",
    "horror game story animation",

    # INDONESIA
    "sakura school simulator cerita seram",
    "roblox cerita horor animasi",
    "minecraft cerita horor seram",
    "animasi horor sekolah viral",
    "cerita seram animasi pendek",
]

# Berapa hasil maksimal per keyword (1 page = max 50, kita pakai 25)
MAX_RESULTS_PER_KEYWORD = 25

# Minimal jumlah video yang harus dimiliki channel agar lolos filter
MIN_VIDEO_COUNT = 80

# --- 4. (OPSIONAL) DAFTAR CHANNEL ID YANG SUDAH PUNYA ---
# Supaya tidak muncul dobel di hasil pencarian baru.
# Isi dengan 39 channel ID yang sudah kamu kumpulkan, contoh:
EXISTING_CHANNEL_IDS = set([
    "UChirEQ8Q5iGOMEW3TPOo5_Q",
    "UC4_Ssc1v_P5SrrFjbVG821Q",
    "UCGGwuSrxDFQymf66OdM_-pw",
    "UCvwn9pGVzKmMS6Ssd8R0pog",
    "UCYPSqQRAl-E7SyIAPz-9GDA",
    "UClfw7Mx0Vmh4hDAT0STSohw",
    "UC--QxF30QUdNMP4WpTMe6qg",
    "UCTpb9vZ_xp0_n84lyT-2yqw",
    "UCjJdTnEzXa40iNhxtLc_0Ng",
    "UCcwu2DFi0B9WbLSoqeVH9NQ",
    "UCJ9v-fDARn2Vyl1TX9PfVyA",
    "UCrn4zm6SwhoVgNBMT8J_T4A",
    "UCnzbx11s43-5ncWWwejPVHg",
    "UC98_dcRWqBOF8tGrvRnaWmQ",
    "UC63UrA203WWay62-RA37gCA",
    "UCDP_apI00MkhojUlOFb7gGA",
    "UC4Gumj80pOghE8G7xq4Yxjg",
    "UC4hGmH5sABOA70D4fGb8qNQ",
    "UCg55rJ27zjuqod4Cv0ENqPQ",
    "UCawnfDlDlCLiu1ZTIkygc9w",
    "UCGJ9FqZHdsq1tGSzSyyJpSw",
    "UCcliUkdKk9J_7gdsT3No0Xg",
    "UCFQoE23adk7NSPNhBlanu4w",
    "UCwjojsJdcSNP0UT1R-S6mFA",
    "UCR_J_SntqJh5eXw66d5hJxA",
    "UCFSqAZl3AxxMyaHouB2GKSg",
    "UCc2RL8jvY1rJPuCnJVsIQWw",
    "UCUwP2XkG17aD53fmvYoA6Yw",
    "UCfHi2LIb2D4f1hYzX5de0IA",
    "UCQtoYB7gpftk98WsshIG_fQ",
    "UC7GWXKxiy9_AU9TytEh00eg",
    "UCqkVT_bXF2rTyjdIxapaHbw",
    "UCY_vG2Em4Y4zjOJLmVkiQ1g",
    "UCOTQEQd8Rc_Ny30qhz7K5xA",
    "UC1WSSEbkczMjxJ89TGE58jA",
    "UCFjaPtpDqdMozLOLbcAo7eg",
    "UCs1vLs4_lXRMVytjQLizNdA",
    "UCZhUolzN9vMdkjWrnT9DQ2A",
    "UCqN_7EUWgvARJYXaNRMIGOg",
])

# --- 5. FUNGSI PENCARIAN CHANNEL ---
def search_channels_by_keyword(keyword, max_results=25):
    """
    Mencari channel berdasarkan keyword menggunakan search.list (type=channel).
    Mengembalikan list dict: channel_id, channel_title, keyword.
    """
    results = []
    next_page_token = None
    fetched = 0

    while fetched < max_results:
        try:
            request = youtube.search().list(
                q=keyword,
                type="channel",
                part="snippet",
                maxResults=min(50, max_results - fetched),
                pageToken=next_page_token,
                relevanceLanguage="id",
            )
            response = request.execute()
        except HttpError as e:
            print(f"  [ERROR] Keyword '{keyword}': {e}")
            break

        items = response.get("items", [])
        if not items:
            break

        for item in items:
            channel_id = item["snippet"]["channelId"]
            channel_title = item["snippet"]["channelTitle"]
            results.append({
                "channel_id": channel_id,
                "channel_title": channel_title,
                "keyword_ditemukan": keyword,
            })

        fetched += len(items)
        next_page_token = response.get("nextPageToken")
        if not next_page_token:
            break

        time.sleep(0.3)  # jaga-jaga rate limit

    return results

# --- 5b. FUNGSI AMBIL VIDEO COUNT (BATCH, HEMAT QUOTA) ---
def get_video_counts(channel_ids):
    """
    Mengambil jumlah video (videoCount) untuk daftar channel_id.
    channels.list bisa menerima sampai 50 ID per request -> 1 unit quota per request.
    Mengembalikan dict: {channel_id: video_count}
    """
    video_counts = {}
    channel_ids = list(set(channel_ids))

    for i in range(0, len(channel_ids), 50):
        batch = channel_ids[i:i + 50]
        try:
            request = youtube.channels().list(
                part="statistics",
                id=",".join(batch),
            )
            response = request.execute()
        except HttpError as e:
            print(f"  [ERROR] Gagal ambil statistics untuk batch: {e}")
            continue

        for item in response.get("items", []):
            cid = item["id"]
            count = int(item["statistics"].get("videoCount", 0))
            video_counts[cid] = count

        time.sleep(0.3)

    return video_counts

# --- 6. JALANKAN PENCARIAN UNTUK SEMUA KEYWORD ---
all_results = []

for kw in KEYWORDS:
    print(f"Mencari: {kw} ...")
    res = search_channels_by_keyword(kw, MAX_RESULTS_PER_KEYWORD)
    print(f"  -> ditemukan {len(res)} channel")
    all_results.extend(res)
    time.sleep(0.5)

print(f"\nTotal hasil mentah (sebelum dedup): {len(all_results)}")

# --- 7. BUAT DATAFRAME & DEDUPLIKASI ---
df = pd.DataFrame(all_results)

if not df.empty:
    # Gabungkan keyword jika channel ditemukan dari banyak keyword
    df = (
        df.groupby(["channel_id", "channel_title"])["keyword_ditemukan"]
        .apply(lambda x: ", ".join(sorted(set(x))))
        .reset_index()
    )

    # Hilangkan channel yang sudah ada di daftar existing
    if EXISTING_CHANNEL_IDS:
        before = len(df)
        df = df[~df["channel_id"].isin(EXISTING_CHANNEL_IDS)]
        print(f"Dihilangkan {before - len(df)} channel yang sudah ada di daftar existing.")

    df = df.sort_values("channel_title").reset_index(drop=True)

print(f"Total channel UNIK baru ditemukan: {len(df)}")

# --- 8. FILTER CHANNEL BERDASARKAN JUMLAH VIDEO (>= MIN_VIDEO_COUNT) ---
if not df.empty:
    print(f"\nMengambil jumlah video tiap channel (untuk filter >= {MIN_VIDEO_COUNT} video)...")
    video_counts = get_video_counts(df["channel_id"].tolist())

    df["video_count"] = df["channel_id"].map(video_counts)

    # Channel yang gagal diambil datanya (mis. dihapus/private) akan NaN -> dibuang juga
    before_filter = len(df)
    df = df.dropna(subset=["video_count"])
    df["video_count"] = df["video_count"].astype(int)

    df = df[df["video_count"] >= MIN_VIDEO_COUNT]
    print(f"Channel sebelum filter: {before_filter} -> sesudah filter (>= {MIN_VIDEO_COUNT} video): {len(df)}")

    df = df.sort_values("video_count", ascending=False).reset_index(drop=True)

# --- 9. SIMPAN KE CSV ---
output_path = "channel_baru_horror_brainrot.csv"
df.to_csv(output_path, index=False)
print(f"\nDisimpan ke: {output_path}")

# Tampilkan preview
df.head(20)

Mencari: sakura school simulator horror story ...
  -> ditemukan 25 channel
Mencari: roblox horror story animation ...
  -> ditemukan 25 channel
Mencari: minecraft horror story scary ...
  -> ditemukan 25 channel
Mencari: horror animation school story ...
  -> ditemukan 25 channel
Mencari: scary animation short story ...
  -> ditemukan 25 channel
Mencari: gta 5 horror story animation ...
  -> ditemukan 25 channel
Mencari: creepy animation horror viral ...
  -> ditemukan 25 channel
Mencari: roblox brainrot horror ...
  -> ditemukan 25 channel
Mencari: minecraft jumpscare horror ...
  -> ditemukan 25 channel
Mencari: horror game story animation ...
  -> ditemukan 25 channel
Mencari: sakura school simulator cerita seram ...
  -> ditemukan 25 channel
Mencari: roblox cerita horor animasi ...
  -> ditemukan 25 channel
Mencari: minecraft cerita horor seram ...
  -> ditemukan 25 channel
Mencari: animasi horor sekolah viral ...
  -> ditemukan 25 channel
Mencari: cerita seram animasi pendek ...
  -> ditemukan 25 channel

Total hasil mentah (sebelum dedup): 375
Dihilangkan 4 channel yang sudah ada di daftar existing.
Total channel UNIK baru ditemukan: 318

Mengambil jumlah video tiap channel (untuk filter >= 80 video)...
Channel sebelum filter: 318 -> sesudah filter (>= 80 video): 194

Disimpan ke: channel_baru_horror_brainrot.csv

,channel_id,channel_title,keyword_ditemukan,video_count
0,UCV6mNrW8CrmWtcxWfQXy11g,DarkViperAU,gta 5 horror story animation,5017
1,UCeuTqSaqk32vp1cn8W-8IWg,Bushwhack 18,minecraft jumpscare horror,4921
2,UCMjKNPhYPMegCQ8BqE-UYQA,COCO MEONG,animasi horor sekolah viral,4130
3,UCUG6MpKhlJunvUKt6n_zqrw,KeiKei,roblox cerita horor animasi,4055
4,UCHb7bDmZ5AQJFQrGPntk3fg,Teguh Sugianto,minecraft cerita horor seram,3819
5,UCdZoVLv1XHLLLJTSNcifuDQ,RedHatter,gta 5 horror story animation,3563
6,UCm99c6g9MKBL4lNTlWrjyFQ,Checkpoint,gta 5 horror story animation,3202
7,UC6P2KliQNaLvHMRvGs3bqJg,GamingWithGarry,gta 5 horror story animation,2955
8,UCZBY6V8Lxmwu8gGRBOyO11w,Kubz Scouts,horror game story animation,2923
9,UCe56RtxwepRSyZ-b--SedOw,DangMattSmith,"gta 5 horror story animation, horror game stor...",2769
10,UCz_yrc3BO9ve7UgDGZn4dig,MC Naveed - Minecraft,minecraft jumpscare horror,2472
11,UC7ftRUwi1ATCCEQhD-WPXFg,Baby DeL,roblox cerita horor animasi,2339
12,UCqzxU2_l0r_48-RAy0lBHWg,MOMON,"minecraft cerita horor seram, roblox cerita ho...",2306
13,UCmaSGxFEpa3LvlavKfvbnMQ,VinsAlvin,"minecraft cerita horor seram, roblox cerita ho...",2297
14,UC-g_O9HWb5B0rVDG1hLd5Hw,EYstreem,minecraft horror story scary,2223
15,UCVTKO1D_G19UlK03ezaADag,SNARLED,scary animation short story,2095
16,UCis4Exp9BuIxaroiJqoumuA,Sibeb ACH,"animasi horor sekolah viral, cerita seram anim...",1981
17,UCRkuUgtDAL4XSU5jB40J_wA,Foltyn,roblox brainrot horror,1891
18,UC-I20klktrosJRJxv9aQhew,Laster,minecraft cerita horor seram,1879
19,UCqMurYXWqmhxrg-7mv7drFw,andi ss,roblox cerita horor animasi,1810

In [ ]:
from google.colab import files
files.download(output_path)

In [ ]:


# ============================================================
# YOUTUBE DATA COLLECTOR - SKRIPSI
# Klasifikasi Viral Horror/Brainrot Anak (XGBoost vs LightGBM)
# Google Colab Version
# ============================================================
# OUTPUT KOLOM:
#   video_id, title, description, tags, published_at,
#   duration_seconds, view_count, like_count, comment_count,
#   channel_id, channel_title, channel_subscriber_count,
#   channel_total_views, channel_video_count
# TIDAK ada kolom is_viral — akan dihitung di preprocessing
# ============================================================

# STEP 1: Install & Import
!pip install google-api-python-client pandas tqdm --quiet

import pandas as pd
import time
import random
import re
import json
import os
from datetime import datetime, timezone
from tqdm import tqdm
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# STEP 2: Konfigurasi
API_KEY = "(masukkan API KEY kamu di sini)"   # ← ganti dengan API key kamu
CUTOFF_DATE = datetime(2026, 1, 1, tzinfo=timezone.utc)   # ambil video publishedAt < 2026-01-01
OLDEST_DATE  = datetime(2020, 1, 1, tzinfo=timezone.utc)  # stop pagination jika video sudah terlalu lama
MAX_VIDEOS_PER_CHANNEL = 300
PROGRESS_FILE = "/content/scraping_progress.json"  # resume jika Colab disconnect

youtube = build("youtube", "v3", developerKey=API_KEY)

# STEP 3: Daftar 200 Channel ID
CHANNEL_IDS = [
    "UCV6mNrW8CrmWtcxWfQXy11g", "UCeuTqSaqk32vp1cn8W-8IWg", "UCMjKNPhYPMegCQ8BqE-UYQA",
    "UCUG6MpKhlJunvUKt6n_zqrw", "UCHb7bDmZ5AQJFQrGPntk3fg", "UCdZoVLv1XHLLLJTSNcifuDQ",
    "UCm99c6g9MKBL4lNTlWrjyFQ", "UC6P2KliQNaLvHMRvGs3bqJg", "UCZBY6V8Lxmwu8gGRBOyO11w",
    "UCe56RtxwepRSyZ-b--SedOw", "UCz_yrc3BO9ve7UgDGZn4dig", "UC7ftRUwi1ATCCEQhD-WPXFg",
    "UCqzxU2_l0r_48-RAy0lBHWg", "UCmaSGxFEpa3LvlavKfvbnMQ", "UC-g_O9HWb5B0rVDG1hLd5Hw",
    "UCVTKO1D_G19UlK03ezaADag", "UCis4Exp9BuIxaroiJqoumuA", "UCRkuUgtDAL4XSU5jB40J_wA",
    "UC-I20klktrosJRJxv9aQhew", "UCqMurYXWqmhxrg-7mv7drFw", "UCCiEKK4835FTejF4ogW4P-A",
    "UCBGp_XPj3Oudk207UNw_tAg", "UCiyvg8v3fJNJNcrh_yQUk3w", "UCO87c90DZllM_mAjrb5irpg",
    "UC7YsDqUlM3Y945tFr2edsAQ", "UCFlp6RS46B4KHuyjuEJVMIQ", "UCfYQlpQc8kTubn_sbDSBrvw",
    "UCpViDMEfvur724mBt8tLiHw", "UCOfyvsftRqM5yyqpT392b4A", "UC6Wl77tvLJCAZDlzq2CWJhg",
    "UCPNoCO-IKY1PIQZCUqf4OfA", "UCRAonprTt59CIOAqXrX0bPg", "UClxdDtMfv9h63-Zp5R81FKw",
    "UC9vKBg57CQ0jjZtaPsXBL6w", "UCMOB6uDg7e-h8OuCw8dK2_Q", "UCRrZWZ8p_Jvhjc8w2KW3EBg",
    "UCp-23W7bSmM_hsfQoWylw7A", "UCt3mMVAyGhwQb_ZBGp_p85g", "UC72VA1LrWHlY86RBbMwGRxw",
    "UCYzEMRKqrh01-tauv7MYyVQ", "UC8Z766VdGCg9sSySmeL-APQ", "UCijMyqnCWgtIUKamfPMvLng",
    "UCpJ6Dn01AqjvFVN2EiK72Ag", "UCr_s2VHtNnGH8LngWlsoZhw", "UC3RYNOKIpKE_2P-5ZapWIYg",
    "UCel2B-6wZhvQHRAKXmpm1Ew", "UCHudxWzwLDAr06TWFmrP7hQ", "UCeI90iCLm4RrNguS4WwNVVQ",
    "UC1cu3C3XRmGee8b1jifMQWA", "UCToxKVrkEuAONR4rFIJ_DyQ", "UCP7k9JoHWrOfbh0slnSOn4g",
    "UCkRNRz9ifB2A04zTb6Y9LYg", "UCbzKhDKRa4YznUc1_f0SBtw", "UCWXcdemE-1OGDhaSAPAw-4w",
    "UCL8_vmF3_0473VvfU7Hi1ug", "UCZVTAKSm7iwy0xX1FyK1VEQ", "UCZvpRu_dNQz1EiFMs4_RNbw",
    "UCVYpWgVdCz0tWUvJmMm25LQ", "UCn4RkjqDN4UE0Uy3y1-K6_w", "UChu9w8GFik0spCfQGF_i9WQ",
    "UCLbvwjbu3Qr0m2EmHHnXC5w", "UCZ9zJNZDmuQQ7Uw97Kdjwkw", "UC9F0hCyH1fa1MrJIfTbSrbw",
    "UCaX76ChBGYNPlcTEGIJSqig", "UCBaJVMx5fcWOHsmPH3IxKKQ", "UCcca5ffHmgRrEwr-9IW-7Uw",
    "UCF3gRq4LbNVVR8QfFUyyTCg", "UCKLyFxoYvEVG-dsELqFlh1Q", "UCm3N3fP3lTgtr2M9svV1sJw",
    "UCF_auq-M9F2Wk4IzIJoHfgg", "UCewhVXvwUtIczThrKiiD-NQ", "UC0XWC2_UZMkXPGn4bj0R2Uw",
    "UCnM02drQP-dF7WMgtJHR4Xw", "UClU1R-QbUDvThzMjMX7NQjQ", "UC261_KcN9A6EIie_Rq0vlWg",
    "UC7h-brAMKgiyrh_BmdhKK3w", "UCiVJZlfcmWMUiXv5oywnDhQ", "UCvCzXDxkH2y32c7VZojgXWA",
    "UCYC3WWrqFERLEnE9jPkRMvw", "UCsCAWoG-SagS7aFuWT1IZPw", "UCMByd3qDySZD1pNmK0ZkmYg",
    "UCZt-N6QkaEnQ4YGDSWdNdPA", "UCgklEUQ8_UR8UY510UFbkxQ", "UChIjAP6RSD0hVWg4fqUdIkA",
    "UCmr_vYKbp98f6kdRoer0iVw", "UCj2Pn8nWcMGnDOdzstvVnbA", "UCph79h9QwbmGwINn45iX5xw",
    "UCQFWbPizb7e8IoM8kvs55cw", "UC7hVpCUJxZD0ACqGQ3zpJ9g", "UCjIctE36xq0SPJoeR8LO5kA",
    "UCRwUO6OIA2DvQA8L1VuzovQ", "UC5IA7MpYcbhbA28RgyQrV0A", "UCOb-ws0S8DmfU4nq4M4z6Rw",
    "UCGkM55uBaAoZziazvvGUlYw", "UC8jqXuCZu7SmpdcNW8hm48Q", "UC6gY0ndnF7q7uTYoZ8Yst5A",
    "UCghiByJ7oj0iu5phWfosLWw", "UCj1g6-RzNx4hvVE4IMzAWuA", "UCUJ0K_e0ac1vBBqss99wudQ",
    "UC8BzE8H7qoFa60JjaRgmIfg", "UCnv6jJ0cdl81j1oWQYbXcsw", "UCaw5JMrP0vgzOHhUKRrxx5g",
    "UCOC5YUqfdbwlnpeMfSTx26Q", "UCVAwRh03m3_1pZjRKvelomA", "UCU0Gd4GEr9rBTIdZC6U3v6w",
    "UCsWwltHud8jAo7txdIOqMSg", "UCCFKfO6XSZ_qEd3kZeOK2Ew", "UC7GZguUCh8gdEs-VKhWqkWA",
    "UC5vY06NlKGpFLTHtMuVoxhw", "UCRu5CV_BaUwJ5QCnunHKvkg", "UCGr3xDf5W2bh0l7o9BQB1oA",
    "UC95VQDMjwvr7GsejfIdS6GQ", "UCquckvYObYDVfMc7ODQ-_WQ", "UCudi3Og-hkRW0HRkiWj2LVw",
    "UCTjF8TNC7blVsBtWyMrsj4A", "UCRnI8mSAO35rx7T4-BFLxtA", "UCS3Iac7JbyHzuXmYj34weRw",
    "UC8b-bA_uLbZHRretA5FK_JQ", "UCyK5hrNdv4293IyUXs19wXw", "UCS8uIXvlSK3HtC0p0VIWyTQ",
    "UCwCKddovSCpQ6PNpIf7ORMA", "UCVZ9t0crMOnaOTz2WyWTmSA", "UCcya9e_wl9ql44-Ee3AETkg",
    "UCM-Aqd9IOe9wBCcAL8LTf7w", "UC33b0wkIKmQm3LzUaQTDGUQ", "UC7rnQz9376zpsBRg8_MmHtQ",
    "UCAj92HhkGw2vgxbdtohJ7QA", "UCtk-l_31BDew-izEFTP1V3Q", "UCnUtxiw-APwRWADsXedTufQ",
    "UCK-21bv_K3pgkDDz_Pzcwnw", "UCjX0ISWJK2lhN3FODrUP0HA", "UC_coP4HpCrkEeBgk3vkxKpQ",
    "UC-RQhtMze3BUzskjv7fumpg", "UCi21QsYAY8kw1YjFq16lZyw", "UCcTKyROPRK964GWtxKJZ10A",
    "UCUIAhYBHAPQTNEyBNl54PRw", "UCR3Mbbg6Ui3vRUAwGFFcqLQ", "UC4lT8b7j4Aovm4TTTnR_RVQ",
    "UCzxEaf1k5OqfERmEaSVi8pQ", "UC02tDemqzG7D4Ep3K4D4Ptw", "UCMYevdNaWmPbuIB0PdPc9ZQ",
    "UCMiLo09ZDt1qS3tCZvtztqw", "UC4pTyJ_o9dSr3nI367GbYyA", "UCKSucZoKBFtsBWvDtq8EBjg",
    "UC_abqMV9cMg-TcQju9kXa5g", "UCGi0NdxX2B36hD6WxXdNhFA", "UCAExz9xtSK8M-dA0IDaYZvg",
    "UCXMwCQVey4PhdWFJ6WhAVhA", "UCbQQ8TCALe4GbyxBeKRuReQ", "UCqykeiGoNyY0Lk784NZ8smQ",
    "UCYD71_aakEU0VT6TwsvV1MA", "UCRrR_UV2aJkGlchEtBxh9gg", "UCn7Ef9w8dTXyk9kNgti9aWw",
    "UCJ87OGZu8iQUO8IyACYYREg", "UCQ2ni-j9Hbtbzt9FytvkBUQ", "UCnVGkEmk7_bbnB8opoerEAQ",
    "UC_z0s6xsJB-BNDaW57wHg2g", "UCuK2rjMid48EA6XoQPe4PIA", "UCHrL9XhIqk7LV9Ya6Qa_Hcg",
    "UCFZvDOxST9vb0nX-Z24YTaw", "UCmsed0Kr1fPl-mvp6iM-_9g", "UCRTsD38mMGi7HnWFzlDUFYA",
    "UCMy725vbeMFUdsFvxTO2zVA", "UCubtXu0Sos902zWt2SfOfTA", "UCuuJUQ8vFxTOUX3X_uK45Dw",
    "UCOdTTViMfSVhc32hmii_Ptg", "UC0p6HfB0vLVMDgvkUCsrpHw", "UCw9gSvWYARIPtYSlVv7b6fA",
    "UC40ed2Fp3t64Wl-7y-zWLcA", "UC3QFis16K3OvRO-3magXLwg", "UCRUoCIu-oho_bnMkhCxyrpg",
    "UC9n3IgleIaFrJrp2hipGQpQ", "UCZX5B1TcHWJKbwAQuYwEh_w", "UCHgTQpnZJY6nW3X61JbtP2Q",
    "UC2zbpOnhs0PwkHza5mkpDYQ", "UC2hm5rD_IrfYRMfq5YQudgA", "UCpZLNDzplh9FDioOX-jnvKA",
    "UC12ClG0_7aPLNdRNNl_4zTA", "UCw-WWK1U5Nlds-ydZNCrkcg", "UCfEd-og-67AUEGwUhcUuzqw",
    "UCFNTq9XKHDNy_1-2lL0kqCg", "UCywlrebEcnkJ6m1y9YViWoQ", "UC_6HKUyjbWkU2iZpnvcJdXA",
    "UCkEKvvUyjcBU4izHBL8Jq4A", "UCCyocdgwZVcIfnWzwhVEdLA", "UCTCdn0QxSosQGnaAPgFrBcQ",
    "UC5zayj7sRZ_zHSqwMmduI4g", "UCVlOEP2q7meEoneD5qgeTxw", "UCIgexLjhSyzvitCywx-m3vw",
    "UCfKQqn93rsJjRa8s2DWLrug", "UCCfaWHyOqKfen_-p0b7L0Xw", "UC8rPkG068jFlejCMBDH582w",
    "UCSH77L4K8TrBgVOEdmF3zxw", "UCBp-eiOdKwtEDQ88wqb8fmg"
]
print(f"Total channel: {len(CHANNEL_IDS)}")

# STEP 4: Helper — parse durasi ISO 8601 ke detik
def parse_duration(duration_iso):
    match = re.match(r'PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?', duration_iso or "")
    if not match:
        return 0
    h = int(match.group(1) or 0)
    m = int(match.group(2) or 0)
    s = int(match.group(3) or 0)
    return h * 3600 + m * 60 + s

def parse_dt(iso_str):
    """Parse ISO 8601 string ke datetime UTC."""
    if not iso_str:
        return None
    return datetime.fromisoformat(iso_str.replace("Z", "+00:00"))

# STEP 5: Load/save progress (resume-safe)
def load_progress():
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE, "r") as f:
            return json.load(f)
    return {"done_channels": [], "rows": []}

def save_progress(done_channels, rows):
    with open(PROGRESS_FILE, "w") as f:
        json.dump({"done_channels": done_channels, "rows": rows}, f)

# STEP 6: Ambil data channel + uploads playlist ID (1 API call, bukan 2)
def get_channel_info(channel_id):
    """
    1 call: channels().list(part="snippet,statistics,contentDetails")
    Return: dict info channel + playlist_id uploads
    """
    try:
        resp = youtube.channels().list(
            part="snippet,statistics,contentDetails",
            id=channel_id
        ).execute()

        if not resp.get("items"):
            return None

        item = resp["items"][0]
        stats = item.get("statistics", {})
        playlist_id = (
            item.get("contentDetails", {})
                .get("relatedPlaylists", {})
                .get("uploads", None)
        )
        return {
            "channel_id":                 channel_id,
            "channel_title":              item["snippet"]["title"],
            "channel_subscriber_count":   int(stats.get("subscriberCount", 0)),
            "channel_total_views":        int(stats.get("viewCount", 0)),
            "channel_video_count":        int(stats.get("videoCount", 0)),
            "uploads_playlist_id":        playlist_id,
        }
    except HttpError as e:
        print(f"  [ERROR] channels.list {channel_id}: {e}")
        return None

# STEP 7: Ambil video IDs dari uploads playlist
# Stop paginasi jika sudah lewat OLDEST_DATE (hemat quota)
def get_video_ids_from_playlist(playlist_id, max_videos=300):
    """
    Ambil video IDs dari uploads playlist.
    Stop jika: (a) sudah max_videos, atau (b) video sudah lebih tua dari OLDEST_DATE.
    Return: list of (video_id, published_at_str)
    """
    items_out = []
    next_page = None

    while len(items_out) < max_videos:
        try:
            resp = youtube.playlistItems().list(
                part="contentDetails",
                playlistId=playlist_id,
                maxResults=50,
                pageToken=next_page
            ).execute()
        except HttpError as e:
            print(f"  [ERROR] playlistItems.list: {e}")
            break

        page_items = resp.get("items", [])
        if not page_items:
            break

        stop_early = False
        for item in page_items:
            cd = item.get("contentDetails", {})
            vid_id = cd.get("videoId")
            pub_at = cd.get("videoPublishedAt", "")

            # Cek apakah sudah terlalu lama
            dt = parse_dt(pub_at)
            if dt and dt < OLDEST_DATE:
                stop_early = True
                break

            items_out.append((vid_id, pub_at))
            if len(items_out) >= max_videos:
                stop_early = True
                break

        next_page = resp.get("nextPageToken")
        if stop_early or not next_page:
            break

    return items_out

# STEP 8: Ambil detail video batch (max 50 per call)
def get_video_details_batch(video_id_list, channel_info):
    """
    1 call videos().list untuk maks 50 video ID.
    Filter: publishedAt harus < CUTOFF_DATE (2026-01-01).
    Return: list of row dicts.
    """
    if not video_id_list:
        return []
    try:
        resp = youtube.videos().list(
            part="snippet,statistics,contentDetails",
            id=",".join(video_id_list)
        ).execute()
    except HttpError as e:
        print(f"  [ERROR] videos.list: {e}")
        return []

    rows = []
    for item in resp.get("items", []):
        snippet    = item.get("snippet", {})
        stats      = item.get("statistics", {})
        content    = item.get("contentDetails", {})

        pub_at = snippet.get("publishedAt", "")
        dt = parse_dt(pub_at)

        # Filter: hanya video sebelum 2026
        if dt and dt >= CUTOFF_DATE:
            continue

        tags = snippet.get("tags", [])

        rows.append({
            # --- identitas video ---
            "video_id":                   item.get("id", ""),
            "title":                      snippet.get("title", ""),
            "description":                snippet.get("description", ""),
            "tags":                       "|".join(tags),   # pakai | bukan , supaya tidak confuse CSV
            "published_at":               pub_at,
            "duration_seconds":           parse_duration(content.get("duration", "")),

            # --- engagement (raw, belum ada label viral) ---
            "view_count":                 int(stats.get("viewCount", 0)),
            "like_count":                 int(stats.get("likeCount", 0)),
            "comment_count":              int(stats.get("commentCount", 0)),

            # --- info channel (denormalized, biar 1 file cukup) ---
            "channel_id":                 channel_info["channel_id"],
            "channel_title":              channel_info["channel_title"],
            "channel_subscriber_count":   channel_info["channel_subscriber_count"],
            "channel_total_views":        channel_info["channel_total_views"],
            "channel_video_count":        channel_info["channel_video_count"],
        })
    return rows

# STEP 9: EKSEKUSI SCRAPING (dengan resume)
print("=" * 65)
print("SCRAPING 200 CHANNELS — HORROR/BRAINROT ANAK")
print(f"Filter: publishedAt < 2026-01-01  |  max {MAX_VIDEOS_PER_CHANNEL} video/channel")
print("=" * 65)

progress    = load_progress()
done_ids    = set(progress["done_channels"])
all_rows    = progress["rows"]
failed      = []
quota_used  = 0

remaining = [ch for ch in CHANNEL_IDS if ch not in done_ids]
print(f"Sudah selesai sebelumnya : {len(done_ids)} channel")
print(f"Sisa yang akan diproses  : {len(remaining)} channel\n")

for idx, channel_id in enumerate(tqdm(remaining, desc="Progress")):
    print(f"\n[{len(done_ids)+1}/{len(CHANNEL_IDS)}] {channel_id}")

    # --- ambil info channel (1 call) ---
    ch_info = get_channel_info(channel_id)
    quota_used += 1
    if not ch_info or not ch_info.get("uploads_playlist_id"):
        print(f"  ✗ Skip (channel tidak ditemukan atau tidak ada uploads playlist)")
        failed.append(channel_id)
        done_ids.add(channel_id)
        save_progress(list(done_ids), all_rows)
        continue

    print(f"  ✓ {ch_info['channel_title']} | {ch_info['channel_subscriber_count']:,} subs")

    # --- ambil video IDs (N calls playlistItems.list) ---
    vid_pairs = get_video_ids_from_playlist(
        ch_info["uploads_playlist_id"],
        max_videos=MAX_VIDEOS_PER_CHANNEL
    )
    pages_used = (len(vid_pairs) // 50) + 1
    quota_used += pages_used

    vid_ids = [v[0] for v in vid_pairs if v[0]]
    print(f"  → {len(vid_ids)} video IDs ditemukan ({pages_used} page playlistItems)")

    if not vid_ids:
        done_ids.add(channel_id)
        save_progress(list(done_ids), all_rows)
        continue

    # --- ambil detail video (batch 50, N calls videos.list) ---
    channel_rows = []
    for i in range(0, len(vid_ids), 50):
        batch = vid_ids[i:i+50]
        rows  = get_video_details_batch(batch, ch_info)
        channel_rows.extend(rows)
        quota_used += 1
        time.sleep(0.3)

    all_rows.extend(channel_rows)
    done_ids.add(channel_id)
    print(f"  ✓ {len(channel_rows)} video disimpan | quota terpakai ~{quota_used} unit")

    # --- simpan progress setiap channel ---
    save_progress(list(done_ids), all_rows)

    # delay antar channel
    time.sleep(random.uniform(1.0, 2.0))

# STEP 10: Buat DataFrame & simpan CSV
print("\n" + "=" * 65)
print("MENYIMPAN DATASET")
print("=" * 65)

df = pd.DataFrame(all_rows)

# Buang duplikat video_id (kalau channel overlap)
before = len(df)
df = df.drop_duplicates(subset="video_id").reset_index(drop=True)
print(f"Duplikat video dihapus: {before - len(df)} baris")

# Urutkan dari terbaru
df["published_at"] = pd.to_datetime(df["published_at"], utc=True)
df = df.sort_values("published_at", ascending=False).reset_index(drop=True)

OUTPUT_PATH = "/content/dataset_raw_skripsi.csv"
df.to_csv(OUTPUT_PATH, index=False)

print(f"\n✓ File disimpan: {OUTPUT_PATH}")
print(f"  Total baris  : {len(df):,}")
print(f"  Total kolom  : {len(df.columns)}")
print(f"  Kolom        : {list(df.columns)}")
print(f"  Quota terpakai (estimasi): ~{quota_used} / 10,000 unit")
print(f"  Channel berhasil : {len(done_ids) - len(failed)}")
print(f"  Channel gagal    : {len(failed)}")

# STEP 11: Preview & statistik ringkas
print("\n--- Preview 5 baris pertama ---")
display(df.head())

print("\n--- Statistik engagement ---")
print(df[["view_count","like_count","comment_count","duration_seconds"]].describe().round(0))

print("\n--- Distribusi tahun upload ---")
print(df["published_at"].dt.year.value_counts().sort_index())

# STEP 12: Download
from google.colab import files
files.download(OUTPUT_PATH)
print(f"\n⬇ Download dimulai: dataset_raw_skripsi.csv")

if failed:
    fail_path = "/content/failed_channels.txt"
    with open(fail_path, "w") as f:
        f.write("\n".join(failed))
    files.download(fail_path)
    print(f"⬇ Download dimulai: failed_channels.txt ({len(failed)} channel gagal)")

print("\nSelesai.")

Total channel: 194
=================================================================
SCRAPING 200 CHANNELS — HORROR/BRAINROT ANAK
Filter: publishedAt < 2026-01-01  |  max 300 video/channel
=================================================================
Sudah selesai sebelumnya : 0 channel
Sisa yang akan diproses  : 194 channel

Progress:   0%|          | 0/194 [00:00<?, ?it/s]

[1/194] UCV6mNrW8CrmWtcxWfQXy11g
  ✓ DarkViperAU | 2,210,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~14 unit

Progress:   1%|          | 1/194 [00:06<21:43,  6.75s/it]

[2/194] UCeuTqSaqk32vp1cn8W-8IWg
  ✓ Bushwhack 18 | 3,000,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~28 unit

Progress:   1%|          | 2/194 [00:14<22:40,  7.08s/it]

[3/194] UCMjKNPhYPMegCQ8BqE-UYQA
  ✓ COCO MEONG | 447,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~42 unit

Progress:   2%|▏         | 3/194 [00:20<21:49,  6.85s/it]

[4/194] UCUG6MpKhlJunvUKt6n_zqrw
  ✓ KeiKei | 1,910,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~56 unit

Progress:   2%|▏         | 4/194 [00:26<20:07,  6.36s/it]

[5/194] UCHb7bDmZ5AQJFQrGPntk3fg
  ✓ Teguh Sugianto | 8,080,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 21 video disimpan | quota terpakai ~70 unit

Progress:   3%|▎         | 5/194 [00:32<20:10,  6.40s/it]

[6/194] UCdZoVLv1XHLLLJTSNcifuDQ
  ✓ RedHatter | 2,890,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 300 video disimpan | quota terpakai ~84 unit

Progress:   3%|▎         | 6/194 [00:39<20:35,  6.57s/it]

[7/194] UCm99c6g9MKBL4lNTlWrjyFQ
  ✓ Checkpoint | 4,350,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 197 video disimpan | quota terpakai ~98 unit

Progress:   4%|▎         | 7/194 [00:45<19:30,  6.26s/it]

[8/194] UC6P2KliQNaLvHMRvGs3bqJg
  ✓ GamingWithGarry | 2,870,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 131 video disimpan | quota terpakai ~112 unit

Progress:   4%|▍         | 8/194 [00:51<19:14,  6.21s/it]

[9/194] UCZBY6V8Lxmwu8gGRBOyO11w
  ✓ Kubz Scouts | 6,610,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 146 video disimpan | quota terpakai ~126 unit

Progress:   5%|▍         | 9/194 [00:56<18:26,  5.98s/it]

[10/194] UCe56RtxwepRSyZ-b--SedOw
  ✓ DangMattSmith | 15,200,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 132 video disimpan | quota terpakai ~140 unit

Progress:   5%|▌         | 10/194 [01:02<18:22,  5.99s/it]

[11/194] UCz_yrc3BO9ve7UgDGZn4dig
  ✓ MC Naveed - Minecraft | 3,100,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 279 video disimpan | quota terpakai ~154 unit

Progress:   6%|▌         | 11/194 [01:08<17:52,  5.86s/it]

[12/194] UC7ftRUwi1ATCCEQhD-WPXFg
  ✓ Baby DeL | 1,420,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 133 video disimpan | quota terpakai ~168 unit

Progress:   6%|▌         | 12/194 [01:14<18:19,  6.04s/it]

[13/194] UCqzxU2_l0r_48-RAy0lBHWg
  ✓ MOMON | 3,830,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 154 video disimpan | quota terpakai ~182 unit

Progress:   7%|▋         | 13/194 [01:21<18:59,  6.30s/it]

[14/194] UCmaSGxFEpa3LvlavKfvbnMQ
  ✓ VinsAlvin | 1,710,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 133 video disimpan | quota terpakai ~196 unit

Progress:   7%|▋         | 14/194 [01:28<19:09,  6.39s/it]

[15/194] UC-g_O9HWb5B0rVDG1hLd5Hw
  ✓ EYstreem | 13,700,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 258 video disimpan | quota terpakai ~210 unit

Progress:   8%|▊         | 15/194 [01:34<18:39,  6.25s/it]

[16/194] UCVTKO1D_G19UlK03ezaADag
  ✓ SNARLED | 2,270,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 221 video disimpan | quota terpakai ~224 unit

Progress:   8%|▊         | 16/194 [01:39<17:32,  5.91s/it]

[17/194] UCis4Exp9BuIxaroiJqoumuA
  ✓ Sibeb ACH | 4,000,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 169 video disimpan | quota terpakai ~238 unit

Progress:   9%|▉         | 17/194 [01:45<17:40,  5.99s/it]

[18/194] UCRkuUgtDAL4XSU5jB40J_wA
  ✓ Foltyn | 11,800,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 103 video disimpan | quota terpakai ~252 unit

Progress:   9%|▉         | 18/194 [01:51<17:12,  5.86s/it]

[19/194] UC-I20klktrosJRJxv9aQhew
  ✓ Laster | 3,810,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 67 video disimpan | quota terpakai ~266 unit

Progress:  10%|▉         | 19/194 [01:57<17:20,  5.95s/it]

[20/194] UCqMurYXWqmhxrg-7mv7drFw
  ✓ andi ss | 876,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 29 video disimpan | quota terpakai ~280 unit

Progress:  10%|█         | 20/194 [02:02<16:43,  5.77s/it]

[21/194] UCCiEKK4835FTejF4ogW4P-A
  ✓ jmwFILMS | 1,540,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 217 video disimpan | quota terpakai ~294 unit

Progress:  11%|█         | 21/194 [02:09<17:09,  5.95s/it]

[22/194] UCBGp_XPj3Oudk207UNw_tAg
  ✓ Doni Bobes | 4,510,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 280 video disimpan | quota terpakai ~308 unit

Progress:  11%|█▏        | 22/194 [02:14<16:59,  5.93s/it]

[23/194] UCiyvg8v3fJNJNcrh_yQUk3w
  ✓ Bi Marbi | 1,390,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 47 video disimpan | quota terpakai ~322 unit

Progress:  12%|█▏        | 23/194 [02:21<17:07,  6.01s/it]

[24/194] UCO87c90DZllM_mAjrb5irpg
  ✓ Rizalmaihndra | 2,470,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 130 video disimpan | quota terpakai ~336 unit

Progress:  12%|█▏        | 24/194 [02:26<16:25,  5.80s/it]

[25/194] UC7YsDqUlM3Y945tFr2edsAQ
  ✓ Funny Horror | 2,470,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 282 video disimpan | quota terpakai ~350 unit

Progress:  13%|█▎        | 25/194 [02:31<16:08,  5.73s/it]

[26/194] UCFlp6RS46B4KHuyjuEJVMIQ
  ✓ Sandal Goib | 1,990,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 131 video disimpan | quota terpakai ~364 unit

Progress:  13%|█▎        | 26/194 [02:38<16:44,  5.98s/it]

[27/194] UCfYQlpQc8kTubn_sbDSBrvw
  ✓ Aykhen | 953,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 193 video disimpan | quota terpakai ~378 unit

Progress:  14%|█▍        | 27/194 [02:43<16:08,  5.80s/it]

[28/194] UCpViDMEfvur724mBt8tLiHw
  ✓ Windia Nata | 2,470,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 161 video disimpan | quota terpakai ~392 unit

Progress:  14%|█▍        | 28/194 [02:49<16:01,  5.79s/it]

[29/194] UCOfyvsftRqM5yyqpT392b4A
  ✓ Dash Roblox | 1,480,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~406 unit

Progress:  15%|█▍        | 29/194 [02:54<14:50,  5.40s/it]

[30/194] UC6Wl77tvLJCAZDlzq2CWJhg
  ✓ Vivilly | 1,780,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 129 video disimpan | quota terpakai ~420 unit

Progress:  15%|█▌        | 30/194 [02:59<14:40,  5.37s/it]

[31/194] UCPNoCO-IKY1PIQZCUqf4OfA
  ✓ Draw The Life TikTak | 1,440,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 251 video disimpan | quota terpakai ~434 unit

Progress:  16%|█▌        | 31/194 [03:04<14:30,  5.34s/it]

[32/194] UCRAonprTt59CIOAqXrX0bPg
  ✓ Jundy Juns | 2,500,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 293 video disimpan | quota terpakai ~448 unit

Progress:  16%|█▋        | 32/194 [03:10<14:41,  5.44s/it]

[33/194] UClxdDtMfv9h63-Zp5R81FKw
  ✓ zachbealetv | 768,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 269 video disimpan | quota terpakai ~462 unit

Progress:  17%|█▋        | 33/194 [03:16<14:49,  5.52s/it]

[34/194] UC9vKBg57CQ0jjZtaPsXBL6w
  ✓ Billy Samuel | 5,710,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 193 video disimpan | quota terpakai ~476 unit

Progress:  18%|█▊        | 34/194 [03:21<14:26,  5.41s/it]

[35/194] UCMOB6uDg7e-h8OuCw8dK2_Q
  ✓ ALTER | 3,840,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 237 video disimpan | quota terpakai ~490 unit

Progress:  18%|█▊        | 35/194 [03:26<14:22,  5.43s/it]

[36/194] UCRrZWZ8p_Jvhjc8w2KW3EBg
  ✓ Wansee Entertainment | 1,820,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 264 video disimpan | quota terpakai ~504 unit

Progress:  19%|█▊        | 36/194 [03:32<14:47,  5.61s/it]

[37/194] UCp-23W7bSmM_hsfQoWylw7A
  ✓ ROBLOX TOPIC INDONESIA | 2,020,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 179 video disimpan | quota terpakai ~518 unit

Progress:  19%|█▉        | 37/194 [03:38<14:56,  5.71s/it]

[38/194] UCt3mMVAyGhwQb_ZBGp_p85g
  ✓ Flight Gamer | 8,790,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 131 video disimpan | quota terpakai ~532 unit

Progress:  20%|█▉        | 38/194 [03:43<14:22,  5.53s/it]

[39/194] UC72VA1LrWHlY86RBbMwGRxw
  ✓ Cerita Pendek Remaja | 374,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 164 video disimpan | quota terpakai ~546 unit

Progress:  20%|██        | 39/194 [03:49<14:25,  5.58s/it]

[40/194] UCYzEMRKqrh01-tauv7MYyVQ
  ✓ MSA | 26,900,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 261 video disimpan | quota terpakai ~560 unit

Progress:  21%|██        | 40/194 [03:54<13:55,  5.43s/it]

[41/194] UC8Z766VdGCg9sSySmeL-APQ
  ✓ Here's Johnny | 3,610,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 130 video disimpan | quota terpakai ~574 unit

Progress:  21%|██        | 41/194 [03:59<13:46,  5.40s/it]

[42/194] UCijMyqnCWgtIUKamfPMvLng
  ✓ HeyyVance | 886,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 122 video disimpan | quota terpakai ~588 unit

Progress:  22%|██▏       | 42/194 [04:05<13:33,  5.35s/it]

[43/194] UCpJ6Dn01AqjvFVN2EiK72Ag
  ✓ Crypt TV | 3,770,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 97 video disimpan | quota terpakai ~602 unit

Progress:  22%|██▏       | 43/194 [04:10<13:28,  5.35s/it]

[44/194] UCr_s2VHtNnGH8LngWlsoZhw
  ✓ WANSEE - Alltäglicher Horror Anime | 124,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 275 video disimpan | quota terpakai ~616 unit

Progress:  23%|██▎       | 44/194 [04:15<13:15,  5.30s/it]

[45/194] UC3RYNOKIpKE_2P-5ZapWIYg
  ✓ KingWoolz Games | 1,100,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 178 video disimpan | quota terpakai ~630 unit

Progress:  23%|██▎       | 45/194 [04:21<13:30,  5.44s/it]

[46/194] UCel2B-6wZhvQHRAKXmpm1Ew
  ✓ special edd | 5,870,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 253 video disimpan | quota terpakai ~644 unit

Progress:  24%|██▎       | 46/194 [04:27<13:37,  5.52s/it]

[47/194] UCHudxWzwLDAr06TWFmrP7hQ
  ✓ Johnny and Marty | 9,980,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 32 video disimpan | quota terpakai ~658 unit

Progress:  24%|██▍       | 47/194 [04:32<13:08,  5.36s/it]

[48/194] UCeI90iCLm4RrNguS4WwNVVQ
  ✓ Textify | 475,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 141 video disimpan | quota terpakai ~672 unit

Progress:  25%|██▍       | 48/194 [04:37<12:49,  5.27s/it]

[49/194] UC1cu3C3XRmGee8b1jifMQWA
  ✓ Droomp | 1,700,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 248 video disimpan | quota terpakai ~686 unit

Progress:  25%|██▌       | 49/194 [04:42<12:59,  5.38s/it]

[50/194] UCToxKVrkEuAONR4rFIJ_DyQ
  ✓ GameToons | 12,700,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 239 video disimpan | quota terpakai ~700 unit

Progress:  26%|██▌       | 50/194 [04:48<13:13,  5.51s/it]

[51/194] UCP7k9JoHWrOfbh0slnSOn4g
  ✓ RayGloom Creepypasta | 554,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 256 video disimpan | quota terpakai ~714 unit

Progress:  26%|██▋       | 51/194 [04:54<13:02,  5.47s/it]

[52/194] UCkRNRz9ifB2A04zTb6Y9LYg
  ✓ Gue Punya Cerita | 1,800,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 59 video disimpan | quota terpakai ~728 unit

Progress:  27%|██▋       | 52/194 [05:00<13:22,  5.65s/it]

[53/194] UCbzKhDKRa4YznUc1_f0SBtw
  ✓ Animasi PODTOON | 3,420,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 237 video disimpan | quota terpakai ~742 unit

Progress:  27%|██▋       | 53/194 [05:05<13:18,  5.66s/it]

[54/194] UCWXcdemE-1OGDhaSAPAw-4w
  ✓ squewe | 2,340,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 169 video disimpan | quota terpakai ~756 unit

Progress:  28%|██▊       | 54/194 [05:11<13:16,  5.69s/it]

[55/194] UCL8_vmF3_0473VvfU7Hi1ug
  ✓ MARVEL THE MARVELOUS | 615,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 220 video disimpan | quota terpakai ~770 unit

Progress:  28%|██▊       | 55/194 [05:17<13:35,  5.87s/it]

[56/194] UCZVTAKSm7iwy0xX1FyK1VEQ
  ✓ xKarutaClanx | 961,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 196 video disimpan | quota terpakai ~784 unit

Progress:  29%|██▉       | 56/194 [05:24<13:43,  5.97s/it]

[57/194] UCZvpRu_dNQz1EiFMs4_RNbw
  ✓ IMR Scary Tales | 1,230,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 226 video disimpan | quota terpakai ~798 unit

Progress:  29%|██▉       | 57/194 [05:28<12:49,  5.61s/it]

[58/194] UCVYpWgVdCz0tWUvJmMm25LQ
  ✓ OTTER ON ROBLOX | 709,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 131 video disimpan | quota terpakai ~812 unit

Progress:  30%|██▉       | 58/194 [05:33<12:21,  5.45s/it]

[59/194] UCn4RkjqDN4UE0Uy3y1-K6_w
  ✓ Laughability | 2,820,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 294 video disimpan | quota terpakai ~826 unit

Progress:  30%|███       | 59/194 [05:39<12:15,  5.44s/it]

[60/194] UChu9w8GFik0spCfQGF_i9WQ
  ✓ Dunia Farash ROBLOX | 1,850,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 128 video disimpan | quota terpakai ~840 unit

Progress:  31%|███       | 60/194 [05:44<11:49,  5.30s/it]

[61/194] UCLbvwjbu3Qr0m2EmHHnXC5w
  ✓ ABISOME | 600,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 288 video disimpan | quota terpakai ~854 unit

Progress:  31%|███▏      | 61/194 [05:50<12:00,  5.42s/it]

[62/194] UCZ9zJNZDmuQQ7Uw97Kdjwkw
  ✓ GamerSault | 532,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 262 video disimpan | quota terpakai ~868 unit

Progress:  32%|███▏      | 62/194 [05:55<11:52,  5.40s/it]

[63/194] UC9F0hCyH1fa1MrJIfTbSrbw
  ✓ Keluarga Bokir | 316,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 120 video disimpan | quota terpakai ~882 unit

Progress:  32%|███▏      | 63/194 [06:00<11:52,  5.44s/it]

[64/194] UCaX76ChBGYNPlcTEGIJSqig
  ✓ Cerita Warga | 391,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 217 video disimpan | quota terpakai ~896 unit

Progress:  33%|███▎      | 64/194 [06:07<12:16,  5.66s/it]

[65/194] UCBaJVMx5fcWOHsmPH3IxKKQ
  ✓ Wubzzy | 2,820,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 223 video disimpan | quota terpakai ~910 unit

Progress:  34%|███▎      | 65/194 [06:13<12:29,  5.81s/it]

[66/194] UCcca5ffHmgRrEwr-9IW-7Uw
  ✓ DH Animation | 1,220,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 265 video disimpan | quota terpakai ~924 unit

Progress:  34%|███▍      | 66/194 [06:18<12:00,  5.63s/it]

[67/194] UCF3gRq4LbNVVR8QfFUyyTCg
  ✓ Flush | 1,550,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 213 video disimpan | quota terpakai ~938 unit

Progress:  35%|███▍      | 67/194 [06:24<12:04,  5.70s/it]

[68/194] UCKLyFxoYvEVG-dsELqFlh1Q
  ✓ Funny Horror Animation | 4,660,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 257 video disimpan | quota terpakai ~952 unit

Progress:  35%|███▌      | 68/194 [06:29<11:43,  5.58s/it]

[69/194] UCm3N3fP3lTgtr2M9svV1sJw
  ✓ Serial Toon | 56,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 300 video disimpan | quota terpakai ~966 unit

Progress:  36%|███▌      | 69/194 [06:36<12:11,  5.85s/it]

[70/194] UCF_auq-M9F2Wk4IzIJoHfgg
  ✓ SAKURA Channel | 412,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 242 video disimpan | quota terpakai ~980 unit

Progress:  36%|███▌      | 70/194 [06:41<11:44,  5.68s/it]

[71/194] UCewhVXvwUtIczThrKiiD-NQ
  ✓ MJV Animations | 590,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 212 video disimpan | quota terpakai ~994 unit

Progress:  37%|███▋      | 71/194 [06:47<11:57,  5.84s/it]

[72/194] UC0XWC2_UZMkXPGn4bj0R2Uw
  ✓ Scary Pumpkin | 3,670,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 253 video disimpan | quota terpakai ~1008 unit

Progress:  37%|███▋      | 72/194 [06:53<11:44,  5.77s/it]

[73/194] UCnM02drQP-dF7WMgtJHR4Xw
  ✓ Mr. Nightmare | 7,100,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 254 video disimpan | quota terpakai ~1022 unit

Progress:  38%|███▊      | 73/194 [06:58<11:26,  5.68s/it]

[74/194] UClU1R-QbUDvThzMjMX7NQjQ
  ✓ Broccoli Animations | 219,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 258 video disimpan | quota terpakai ~1036 unit

Progress:  38%|███▊      | 74/194 [07:03<10:56,  5.47s/it]

[75/194] UC261_KcN9A6EIie_Rq0vlWg
  ✓ Lovely Gaming | 2,100,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 300 video disimpan | quota terpakai ~1050 unit

Progress:  39%|███▊      | 75/194 [07:09<10:56,  5.52s/it]

[76/194] UC7h-brAMKgiyrh_BmdhKK3w
  ✓ IamRocker | 1,210,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 264 video disimpan | quota terpakai ~1064 unit

Progress:  39%|███▉      | 76/194 [07:15<11:04,  5.63s/it]

[77/194] UCiVJZlfcmWMUiXv5oywnDhQ
  ✓ Wifies | 3,770,000 subs
  → 171 video IDs ditemukan (4 page playlistItems)
  ✓ 170 video disimpan | quota terpakai ~1073 unit

Progress:  40%|███▉      | 77/194 [07:19<10:29,  5.38s/it]

[78/194] UCvCzXDxkH2y32c7VZojgXWA
  ✓ SSG Animations | 189,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 194 video disimpan | quota terpakai ~1087 unit

Progress:  40%|████      | 78/194 [07:25<10:36,  5.49s/it]

[79/194] UCYC3WWrqFERLEnE9jPkRMvw
  ✓ BaconHair Originals | 771,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 285 video disimpan | quota terpakai ~1101 unit

Progress:  41%|████      | 79/194 [07:31<10:42,  5.58s/it]

[80/194] UCsCAWoG-SagS7aFuWT1IZPw
  ✓ Horror Shorts Party | 1,620,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 251 video disimpan | quota terpakai ~1115 unit

Progress:  41%|████      | 80/194 [07:37<10:33,  5.55s/it]

[81/194] UCMByd3qDySZD1pNmK0ZkmYg
  ✓ Proyekto Helmo | 715,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 219 video disimpan | quota terpakai ~1129 unit

Progress:  42%|████▏     | 81/194 [07:42<10:28,  5.56s/it]

[82/194] UCZt-N6QkaEnQ4YGDSWdNdPA
  ✓ Bobarose19 | 1,380,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 181 video disimpan | quota terpakai ~1143 unit

Progress:  42%|████▏     | 82/194 [07:48<10:19,  5.53s/it]

[83/194] UCgklEUQ8_UR8UY510UFbkxQ
  ✓ Mipan & Zuzuzu ROBLOX | 921,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 152 video disimpan | quota terpakai ~1157 unit

Progress:  43%|████▎     | 83/194 [07:53<10:13,  5.53s/it]

[84/194] UChIjAP6RSD0hVWg4fqUdIkA
  ✓ Funny Horror School | 931,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 256 video disimpan | quota terpakai ~1171 unit

Progress:  43%|████▎     | 84/194 [07:59<10:20,  5.64s/it]

[85/194] UCmr_vYKbp98f6kdRoer0iVw
  ✓ PrestonGamez | 4,960,000 subs
  → 283 video IDs ditemukan (6 page playlistItems)
  ✓ 184 video disimpan | quota terpakai ~1184 unit

Progress:  44%|████▍     | 85/194 [08:04<09:51,  5.42s/it]

[86/194] UCj2Pn8nWcMGnDOdzstvVnbA
  ✓ Minecraft Curios | 1,650,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 294 video disimpan | quota terpakai ~1198 unit

Progress:  44%|████▍     | 86/194 [08:09<09:46,  5.43s/it]

[87/194] UCph79h9QwbmGwINn45iX5xw
  ✓ Gloomy Sunday Club | 634,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 292 video disimpan | quota terpakai ~1212 unit

Progress:  45%|████▍     | 87/194 [08:14<09:30,  5.33s/it]

[88/194] UCQFWbPizb7e8IoM8kvs55cw
  ✓ Lestari Rifu | 282,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 275 video disimpan | quota terpakai ~1226 unit

Progress:  45%|████▌     | 88/194 [08:20<09:46,  5.53s/it]

[89/194] UC7hVpCUJxZD0ACqGQ3zpJ9g
  ✓ Bloxy Horror Stories | 1,820,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 156 video disimpan | quota terpakai ~1240 unit

Progress:  46%|████▌     | 89/194 [08:26<09:37,  5.50s/it]

[90/194] UCjIctE36xq0SPJoeR8LO5kA
  ✓ SD ANIMATOR | 432,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 278 video disimpan | quota terpakai ~1254 unit

Progress:  46%|████▋     | 90/194 [08:31<09:20,  5.39s/it]

[91/194] UCRwUO6OIA2DvQA8L1VuzovQ
  ✓ SSS Scary Shorts Stories | 49,700 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 276 video disimpan | quota terpakai ~1268 unit

Progress:  47%|████▋     | 91/194 [08:37<09:22,  5.46s/it]

[92/194] UC5IA7MpYcbhbA28RgyQrV0A
  ✓ animasinopal | 11,500,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 276 video disimpan | quota terpakai ~1282 unit

Progress:  47%|████▋     | 92/194 [08:43<09:41,  5.70s/it]

[93/194] UCOb-ws0S8DmfU4nq4M4z6Rw
  ✓ Aimin | 2,200,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 280 video disimpan | quota terpakai ~1296 unit

Progress:  48%|████▊     | 93/194 [08:48<09:30,  5.65s/it]

[94/194] UCGkM55uBaAoZziazvvGUlYw
  ✓ PuaNuggie | 234,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 260 video disimpan | quota terpakai ~1310 unit

Progress:  48%|████▊     | 94/194 [08:55<09:51,  5.92s/it]

[95/194] UC8jqXuCZu7SmpdcNW8hm48Q
  ✓ Cacao Cha | 956,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 270 video disimpan | quota terpakai ~1324 unit

Progress:  49%|████▉     | 95/194 [09:01<10:03,  6.09s/it]

[96/194] UC6gY0ndnF7q7uTYoZ8Yst5A
  ✓ Scary Baboon | 208,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 125 video disimpan | quota terpakai ~1338 unit

Progress:  49%|████▉     | 96/194 [09:07<09:55,  6.08s/it]

[97/194] UCghiByJ7oj0iu5phWfosLWw
  ✓ ManySpider | 1,610,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 172 video disimpan | quota terpakai ~1352 unit

Progress:  50%|█████     | 97/194 [09:14<09:58,  6.17s/it]

[98/194] UCj1g6-RzNx4hvVE4IMzAWuA
  ✓ Edwin | 1,460,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 297 video disimpan | quota terpakai ~1366 unit

Progress:  51%|█████     | 98/194 [09:20<09:38,  6.03s/it]

[99/194] UCUJ0K_e0ac1vBBqss99wudQ
  ✓ PaYuDan | 9,140,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 289 video disimpan | quota terpakai ~1380 unit

Progress:  51%|█████     | 99/194 [09:26<09:42,  6.13s/it]

[100/194] UC8BzE8H7qoFa60JjaRgmIfg
  ✓ Animated Stories | 731,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 269 video disimpan | quota terpakai ~1394 unit

Progress:  52%|█████▏    | 100/194 [09:32<09:26,  6.03s/it]

[101/194] UCnv6jJ0cdl81j1oWQYbXcsw
  ✓ TORNADO | 1,730,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 258 video disimpan | quota terpakai ~1408 unit

Progress:  52%|█████▏    | 101/194 [09:38<09:24,  6.07s/it]

[102/194] UCaw5JMrP0vgzOHhUKRrxx5g
  ✓  Afiq Kentang | 140,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 296 video disimpan | quota terpakai ~1422 unit

Progress:  53%|█████▎    | 102/194 [09:44<09:20,  6.10s/it]

[103/194] UCOC5YUqfdbwlnpeMfSTx26Q
  ✓ CashPlays | 1,090,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 265 video disimpan | quota terpakai ~1436 unit

Progress:  53%|█████▎    | 103/194 [09:50<09:06,  6.00s/it]

[104/194] UCVAwRh03m3_1pZjRKvelomA
  ✓ Dasi Gantung | 6,070,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 289 video disimpan | quota terpakai ~1450 unit

Progress:  54%|█████▎    | 104/194 [09:55<08:43,  5.82s/it]

[105/194] UCU0Gd4GEr9rBTIdZC6U3v6w
  ✓ Aryan 2 Toonz | 2,610,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 281 video disimpan | quota terpakai ~1464 unit

Progress:  54%|█████▍    | 105/194 [10:01<08:25,  5.67s/it]

[106/194] UCsWwltHud8jAo7txdIOqMSg
  ✓ Chiefxd | 729,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 227 video disimpan | quota terpakai ~1478 unit

Progress:  55%|█████▍    | 106/194 [10:06<08:23,  5.72s/it]

[107/194] UCCFKfO6XSZ_qEd3kZeOK2Ew
  ✓ Mort | 539,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 279 video disimpan | quota terpakai ~1492 unit

Progress:  55%|█████▌    | 107/194 [10:12<08:17,  5.71s/it]

[108/194] UC7GZguUCh8gdEs-VKhWqkWA
  ✓ Riri - Magic Tales | 2,700,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 256 video disimpan | quota terpakai ~1506 unit

Progress:  56%|█████▌    | 108/194 [10:17<07:59,  5.58s/it]

[109/194] UC5vY06NlKGpFLTHtMuVoxhw
  ✓ Jaya Animation | 20,700 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 290 video disimpan | quota terpakai ~1520 unit

Progress:  56%|█████▌    | 109/194 [10:23<07:58,  5.63s/it]

[110/194] UCRu5CV_BaUwJ5QCnunHKvkg
  ✓ Fireside Horror | 15,600 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 245 video disimpan | quota terpakai ~1534 unit

Progress:  57%|█████▋    | 110/194 [10:30<08:16,  5.92s/it]

[111/194] UCGr3xDf5W2bh0l7o9BQB1oA
  ✓ Martin Animations | 336,000 subs
  → 298 video IDs ditemukan (6 page playlistItems)
  ✓ 276 video disimpan | quota terpakai ~1547 unit

Progress:  57%|█████▋    | 111/194 [10:35<07:54,  5.71s/it]

[112/194] UC95VQDMjwvr7GsejfIdS6GQ
  ✓ Cartoon Horror Show  | 74,700 subs
  → 297 video IDs ditemukan (6 page playlistItems)
  ✓ 257 video disimpan | quota terpakai ~1560 unit

Progress:  58%|█████▊    | 112/194 [10:41<07:53,  5.77s/it]

[113/194] UCquckvYObYDVfMc7ODQ-_WQ
  ✓ Sakura horror  | 7,090 subs
  → 291 video IDs ditemukan (6 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~1573 unit

Progress:  58%|█████▊    | 113/194 [10:47<08:03,  5.97s/it]

[114/194] UCudi3Og-hkRW0HRkiWj2LVw
  ✓ DogeStory | 545,000 subs
  → 288 video IDs ditemukan (6 page playlistItems)
  ✓ 288 video disimpan | quota terpakai ~1586 unit

Progress:  59%|█████▉    | 114/194 [10:53<07:55,  5.95s/it]

[115/194] UCTjF8TNC7blVsBtWyMrsj4A
  ✓ Horror Skunx | 8,800,000 subs
  → 283 video IDs ditemukan (6 page playlistItems)
  ✓ 265 video disimpan | quota terpakai ~1599 unit

Progress:  59%|█████▉    | 115/194 [10:59<07:39,  5.81s/it]

[116/194] UCRnI8mSAO35rx7T4-BFLxtA
  ✓ DEFUSED DEVIL | 444,000 subs
  → 282 video IDs ditemukan (6 page playlistItems)
  ✓ 249 video disimpan | quota terpakai ~1612 unit

Progress:  60%|█████▉    | 116/194 [11:04<07:31,  5.79s/it]

[117/194] UCS3Iac7JbyHzuXmYj34weRw
  ✓ Swayle | 1,230,000 subs
  → 273 video IDs ditemukan (6 page playlistItems)
  ✓ 214 video disimpan | quota terpakai ~1625 unit

Progress:  60%|██████    | 117/194 [11:10<07:11,  5.61s/it]

[118/194] UC8b-bA_uLbZHRretA5FK_JQ
  ✓ Zachobuilds | 745,000 subs
  → 240 video IDs ditemukan (5 page playlistItems)
  ✓ 237 video disimpan | quota terpakai ~1636 unit

Progress:  61%|██████    | 118/194 [11:15<06:51,  5.41s/it]

[119/194] UCyK5hrNdv4293IyUXs19wXw
  ✓ DEFUSED DEVIL 2.0 | 301,000 subs
  → 269 video IDs ditemukan (6 page playlistItems)
  ✓ 214 video disimpan | quota terpakai ~1649 unit

Progress:  61%|██████▏   | 119/194 [11:20<06:54,  5.53s/it]

[120/194] UCS8uIXvlSK3HtC0p0VIWyTQ
  ✓ TheLoudDude | 4,920,000 subs
  → 268 video IDs ditemukan (6 page playlistItems)
  ✓ 260 video disimpan | quota terpakai ~1662 unit

Progress:  62%|██████▏   | 120/194 [11:26<06:54,  5.60s/it]

[121/194] UCwCKddovSCpQ6PNpIf7ORMA
  ✓ HORROR STORY JOKE | 390,000 subs
  → 262 video IDs ditemukan (6 page playlistItems)
  ✓ 239 video disimpan | quota terpakai ~1675 unit

Progress:  62%|██████▏   | 121/194 [11:32<07:01,  5.78s/it]

[122/194] UCVZ9t0crMOnaOTz2WyWTmSA
  ✓ Calvin | 779,000 subs
  → 261 video IDs ditemukan (6 page playlistItems)
  ✓ 245 video disimpan | quota terpakai ~1688 unit

Progress:  63%|██████▎   | 122/194 [11:37<06:36,  5.51s/it]

[123/194] UCcya9e_wl9ql44-Ee3AETkg
  ✓ Cam2r Gaming | 139,000 subs
  → 261 video IDs ditemukan (6 page playlistItems)
  ✓ 227 video disimpan | quota terpakai ~1701 unit

Progress:  63%|██████▎   | 123/194 [11:43<06:29,  5.48s/it]

[124/194] UCM-Aqd9IOe9wBCcAL8LTf7w
  ✓ RayGloom Creepypasta BEDROCK | 86,000 subs
  → 259 video IDs ditemukan (6 page playlistItems)
  ✓ 219 video disimpan | quota terpakai ~1714 unit

Progress:  64%|██████▍   | 124/194 [11:48<06:23,  5.48s/it]

[125/194] UC33b0wkIKmQm3LzUaQTDGUQ
  ✓ True Horror Stories POV | 401,000 subs
  → 253 video IDs ditemukan (6 page playlistItems)
  ✓ 195 video disimpan | quota terpakai ~1727 unit

Progress:  64%|██████▍   | 125/194 [11:53<06:11,  5.39s/it]

[126/194] UC7rnQz9376zpsBRg8_MmHtQ
  ✓ Ayano cchi | 4,140,000 subs
  → 249 video IDs ditemukan (5 page playlistItems)
  ✓ 235 video disimpan | quota terpakai ~1738 unit

Progress:  65%|██████▍   | 126/194 [11:58<06:01,  5.31s/it]

[127/194] UCAj92HhkGw2vgxbdtohJ7QA
  ✓ GTA 5 SIREN HEAD | 2,270 subs
  → 232 video IDs ditemukan (5 page playlistItems)
  ✓ 232 video disimpan | quota terpakai ~1749 unit

Progress:  65%|██████▌   | 127/194 [12:04<05:54,  5.29s/it]

[128/194] UCtk-l_31BDew-izEFTP1V3Q
  ✓ Capybara Roblox | 668,000 subs
  → 227 video IDs ditemukan (5 page playlistItems)
  ✓ 208 video disimpan | quota terpakai ~1760 unit

Progress:  66%|██████▌   | 128/194 [12:09<05:43,  5.21s/it]

[129/194] UCnUtxiw-APwRWADsXedTufQ
  ✓ Wansee - Hindi Horror Stories Animated | 276,000 subs
  → 197 video IDs ditemukan (4 page playlistItems)
  ✓ 197 video disimpan | quota terpakai ~1769 unit

Progress:  66%|██████▋   | 129/194 [12:14<05:36,  5.18s/it]

[130/194] UCK-21bv_K3pgkDDz_Pzcwnw
  ✓ JJ and Mikey Roblox | 17,600 subs
  → 216 video IDs ditemukan (5 page playlistItems)
  ✓ 48 video disimpan | quota terpakai ~1780 unit

Progress:  67%|██████▋   | 130/194 [12:19<05:28,  5.13s/it]

[131/194] UCjX0ISWJK2lhN3FODrUP0HA
  ✓ Lia Roblox | 496,000 subs
  → 215 video IDs ditemukan (5 page playlistItems)
  ✓ 111 video disimpan | quota terpakai ~1791 unit

Progress:  68%|██████▊   | 131/194 [12:25<05:41,  5.42s/it]

[132/194] UC_coP4HpCrkEeBgk3vkxKpQ
  ✓ Hana Sakura Horor | 1,370,000 subs
  → 209 video IDs ditemukan (5 page playlistItems)
  ✓ 191 video disimpan | quota terpakai ~1802 unit

Progress:  68%|██████▊   | 132/194 [12:30<05:27,  5.29s/it]

[133/194] UC-RQhtMze3BUzskjv7fumpg
  ✓ Mooci & Milo Minecraft | 162,000 subs
  → 210 video IDs ditemukan (5 page playlistItems)
  ✓ 65 video disimpan | quota terpakai ~1813 unit

Progress:  69%|██████▊   | 133/194 [12:35<05:15,  5.17s/it]

[134/194] UCi21QsYAY8kw1YjFq16lZyw
  ✓ Gabbry Roblox | 416,000 subs
  → 208 video IDs ditemukan (5 page playlistItems)
  ✓ 107 video disimpan | quota terpakai ~1824 unit

Progress:  69%|██████▉   | 134/194 [12:40<05:02,  5.05s/it]

[135/194] UCcTKyROPRK964GWtxKJZ10A
  ✓ LilyAnimationz ROBLOX  | 6,050 subs
  → 207 video IDs ditemukan (5 page playlistItems)
  ✓ 163 video disimpan | quota terpakai ~1835 unit

Progress:  70%|██████▉   | 135/194 [12:45<05:13,  5.32s/it]

[136/194] UCUIAhYBHAPQTNEyBNl54PRw
  ✓ Teterong | 331,000 subs
  → 203 video IDs ditemukan (5 page playlistItems)
  ✓ 203 video disimpan | quota terpakai ~1846 unit

Progress:  70%|███████   | 136/194 [12:51<05:07,  5.30s/it]

[137/194] UCR3Mbbg6Ui3vRUAwGFFcqLQ
  ✓ Story Rants | 137,000 subs
  → 203 video IDs ditemukan (5 page playlistItems)
  ✓ 44 video disimpan | quota terpakai ~1857 unit

Progress:  71%|███████   | 137/194 [12:56<05:02,  5.30s/it]

[138/194] UC4lT8b7j4Aovm4TTTnR_RVQ
  ✓ Rizka CH | 2,900,000 subs
  → 198 video IDs ditemukan (4 page playlistItems)
  ✓ 193 video disimpan | quota terpakai ~1866 unit

Progress:  71%|███████   | 138/194 [13:01<04:43,  5.07s/it]

[139/194] UCzxEaf1k5OqfERmEaSVi8pQ
  ✓ Peppa Scary | 21,000 subs
  → 184 video IDs ditemukan (4 page playlistItems)
  ✓ 178 video disimpan | quota terpakai ~1875 unit

Progress:  72%|███████▏  | 139/194 [13:05<04:28,  4.89s/it]

[140/194] UC02tDemqzG7D4Ep3K4D4Ptw
  ✓ Jibonto Animation | 1,960,000 subs
  → 164 video IDs ditemukan (4 page playlistItems)
  ✓ 149 video disimpan | quota terpakai ~1884 unit

Progress:  72%|███████▏  | 140/194 [13:10<04:21,  4.84s/it]

[141/194] UCMYevdNaWmPbuIB0PdPc9ZQ
  ✓ ZMDE | 2,870,000 subs
  → 179 video IDs ditemukan (4 page playlistItems)
  ✓ 176 video disimpan | quota terpakai ~1893 unit

Progress:  73%|███████▎  | 141/194 [13:14<04:07,  4.67s/it]

[142/194] UCMiLo09ZDt1qS3tCZvtztqw
  ✓ RageElixir - Minecraft | 185,000 subs
  → 176 video IDs ditemukan (4 page playlistItems)
  ✓ 167 video disimpan | quota terpakai ~1902 unit

Progress:  73%|███████▎  | 142/194 [13:19<04:06,  4.74s/it]

[143/194] UC4pTyJ_o9dSr3nI367GbYyA
  ✓ SenPrista | 296,000 subs
  → 174 video IDs ditemukan (4 page playlistItems)
  ✓ 168 video disimpan | quota terpakai ~1911 unit

Progress:  74%|███████▎  | 143/194 [13:23<03:51,  4.53s/it]

[144/194] UCKSucZoKBFtsBWvDtq8EBjg
  ✓ Aryan Toonz | 1,290,000 subs
  → 170 video IDs ditemukan (4 page playlistItems)
  ✓ 169 video disimpan | quota terpakai ~1920 unit

Progress:  74%|███████▍  | 144/194 [13:27<03:40,  4.42s/it]

[145/194] UC_abqMV9cMg-TcQju9kXa5g
  ✓ Silkypooh OJT | 14,300 subs
  → 142 video IDs ditemukan (3 page playlistItems)
  ✓ 142 video disimpan | quota terpakai ~1927 unit

Progress:  75%|███████▍  | 145/194 [13:31<03:31,  4.33s/it]

[146/194] UCGi0NdxX2B36hD6WxXdNhFA
  ✓ Audrey Firly | 430,000 subs
  → 167 video IDs ditemukan (4 page playlistItems)
  ✓ 159 video disimpan | quota terpakai ~1936 unit

Progress:  75%|███████▌  | 146/194 [13:36<03:34,  4.46s/it]

[147/194] UCAExz9xtSK8M-dA0IDaYZvg
  ✓ Afaq Hub | 133,000 subs
  → 166 video IDs ditemukan (4 page playlistItems)
  ✓ 145 video disimpan | quota terpakai ~1945 unit

Progress:  76%|███████▌  | 147/194 [13:40<03:28,  4.44s/it]

[148/194] UCXMwCQVey4PhdWFJ6WhAVhA
  ✓ Socks Animations  | 2,450,000 subs
  → 162 video IDs ditemukan (4 page playlistItems)
  ✓ 143 video disimpan | quota terpakai ~1954 unit

Progress:  76%|███████▋  | 148/194 [13:45<03:25,  4.47s/it]

[149/194] UCbQQ8TCALe4GbyxBeKRuReQ
  ✓ cat human | 504,000 subs
  → 157 video IDs ditemukan (4 page playlistItems)
  ✓ 139 video disimpan | quota terpakai ~1963 unit

Progress:  77%|███████▋  | 149/194 [13:50<03:28,  4.63s/it]

[150/194] UCqykeiGoNyY0Lk784NZ8smQ
  ✓ MIR Channel | 2,560,000 subs
  → 153 video IDs ditemukan (4 page playlistItems)
  ✓ 144 video disimpan | quota terpakai ~1972 unit

Progress:  77%|███████▋  | 150/194 [13:55<03:22,  4.61s/it]

[151/194] UCYD71_aakEU0VT6TwsvV1MA
  ✓ Hadi Art Tv | 123,000 subs
  → 145 video IDs ditemukan (3 page playlistItems)
  ✓ 126 video disimpan | quota terpakai ~1979 unit

Progress:  78%|███████▊  | 151/194 [13:59<03:16,  4.58s/it]

[152/194] UCRrR_UV2aJkGlchEtBxh9gg
  ✓ Merrily Horror Animations | 111,000 subs
  → 154 video IDs ditemukan (4 page playlistItems)
  ✓ 153 video disimpan | quota terpakai ~1988 unit

Progress:  78%|███████▊  | 152/194 [14:03<03:04,  4.39s/it]

[153/194] UCn7Ef9w8dTXyk9kNgti9aWw
  ✓ BizarreBub | 2,580,000 subs
  → 125 video IDs ditemukan (3 page playlistItems)
  ✓ 122 video disimpan | quota terpakai ~1995 unit

Progress:  79%|███████▉  | 153/194 [14:07<02:50,  4.16s/it]

[154/194] UCJ87OGZu8iQUO8IyACYYREg
  ✓ Hai Karina | 47,400 subs
  → 155 video IDs ditemukan (4 page playlistItems)
  ✓ 96 video disimpan | quota terpakai ~2004 unit

Progress:  79%|███████▉  | 154/194 [14:11<02:49,  4.24s/it]

[155/194] UCQ2ni-j9Hbtbzt9FytvkBUQ
  ✓ Spacestation Animation | 1,090,000 subs
  → 150 video IDs ditemukan (4 page playlistItems)
  ✓ 139 video disimpan | quota terpakai ~2012 unit

Progress:  80%|███████▉  | 155/194 [14:15<02:40,  4.10s/it]

[156/194] UCnVGkEmk7_bbnB8opoerEAQ
  ✓ Dr. NoSleep | 657,000 subs
  → 148 video IDs ditemukan (3 page playlistItems)
  ✓ 144 video disimpan | quota terpakai ~2019 unit

Progress:  80%|████████  | 156/194 [14:19<02:33,  4.03s/it]

[157/194] UC_z0s6xsJB-BNDaW57wHg2g
  ✓ winterxlaven | 360,000 subs
  → 151 video IDs ditemukan (4 page playlistItems)
  ✓ 97 video disimpan | quota terpakai ~2028 unit

Progress:  81%|████████  | 157/194 [14:23<02:35,  4.20s/it]

[158/194] UCuK2rjMid48EA6XoQPe4PIA
  ✓ Kat-kat Gaming | 240,000 subs
  → 144 video IDs ditemukan (3 page playlistItems)
  ✓ 144 video disimpan | quota terpakai ~2035 unit

Progress:  81%|████████▏ | 158/194 [14:28<02:35,  4.32s/it]

[159/194] UCHrL9XhIqk7LV9Ya6Qa_Hcg
  ✓ Pohon Cerita | 312,000 subs
  → 143 video IDs ditemukan (3 page playlistItems)
  ✓ 118 video disimpan | quota terpakai ~2042 unit

Progress:  82%|████████▏ | 159/194 [14:32<02:31,  4.34s/it]

[160/194] UCFZvDOxST9vb0nX-Z24YTaw
  ✓ ERIG & TIA (ft. INGGRID) | 112,000 subs
  → 139 video IDs ditemukan (3 page playlistItems)
  ✓ 122 video disimpan | quota terpakai ~2049 unit

Progress:  82%|████████▏ | 160/194 [14:37<02:27,  4.34s/it]

[161/194] UCmsed0Kr1fPl-mvp6iM-_9g
  ✓ • It's Lily • | 584,000 subs
  → 137 video IDs ditemukan (3 page playlistItems)
  ✓ 132 video disimpan | quota terpakai ~2056 unit

Progress:  83%|████████▎ | 161/194 [14:41<02:21,  4.30s/it]

[162/194] UCRTsD38mMGi7HnWFzlDUFYA
  ✓ ItsSandwich | 3,200,000 subs
  → 58 video IDs ditemukan (2 page playlistItems)
  ✓ 54 video disimpan | quota terpakai ~2061 unit

Progress:  84%|████████▎ | 162/194 [14:44<02:07,  4.00s/it]

[163/194] UCMy725vbeMFUdsFvxTO2zVA
  ✓ iCharles27 | 62,900 subs
  → 40 video IDs ditemukan (1 page playlistItems)
  ✓ 39 video disimpan | quota terpakai ~2064 unit

Progress:  84%|████████▍ | 163/194 [14:47<01:54,  3.70s/it]

[164/194] UCubtXu0Sos902zWt2SfOfTA
  ✓ Farida | 12,200 subs
  → 135 video IDs ditemukan (3 page playlistItems)
  ✓ 128 video disimpan | quota terpakai ~2071 unit

Progress:  85%|████████▍ | 164/194 [14:51<01:53,  3.77s/it]

[165/194] UCuuJUQ8vFxTOUX3X_uK45Dw
  ✓ Todo Animated Horror | 3,910 subs
  → 134 video IDs ditemukan (3 page playlistItems)
  ✓ 65 video disimpan | quota terpakai ~2078 unit

Progress:  85%|████████▌ | 165/194 [14:55<01:50,  3.81s/it]

[166/194] UCOdTTViMfSVhc32hmii_Ptg
  ✓ DARK & TWISTED  | 128,000 subs
  → 86 video IDs ditemukan (2 page playlistItems)
  ✓ 81 video disimpan | quota terpakai ~2083 unit

Progress:  86%|████████▌ | 166/194 [14:58<01:42,  3.68s/it]

[167/194] UC0p6HfB0vLVMDgvkUCsrpHw
  ✓ ROBLOX BRAİNROT | 7,810 subs
  → 130 video IDs ditemukan (3 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~2090 unit

Progress:  86%|████████▌ | 167/194 [15:03<01:46,  3.94s/it]

[168/194] UCw9gSvWYARIPtYSlVv7b6fA
  ✓ ANOMALY TOONS | 9,290 subs
  → 127 video IDs ditemukan (3 page playlistItems)
  ✓ 109 video disimpan | quota terpakai ~2097 unit

Progress:  87%|████████▋ | 168/194 [15:07<01:42,  3.93s/it]

[169/194] UC40ed2Fp3t64Wl-7y-zWLcA
  ✓ Araw na Itim - Tagalog Animated Horror | 612,000 subs
  → 126 video IDs ditemukan (3 page playlistItems)
  ✓ 123 video disimpan | quota terpakai ~2104 unit

Progress:  87%|████████▋ | 169/194 [15:11<01:42,  4.08s/it]

[170/194] UC3QFis16K3OvRO-3magXLwg
  ✓ Spooky Animation Hindi | 191,000 subs
  → 117 video IDs ditemukan (3 page playlistItems)
  ✓ 109 video disimpan | quota terpakai ~2111 unit

Progress:  88%|████████▊ | 170/194 [15:16<01:42,  4.26s/it]

[171/194] UCRUoCIu-oho_bnMkhCxyrpg
  ✓ NEFF447 | 242,000 subs
  → 124 video IDs ditemukan (3 page playlistItems)
  ✓ 110 video disimpan | quota terpakai ~2118 unit

Progress:  88%|████████▊ | 171/194 [15:20<01:39,  4.33s/it]

[172/194] UC9n3IgleIaFrJrp2hipGQpQ
  ✓ Topi Sihir Animation | 1,550,000 subs
  → 108 video IDs ditemukan (3 page playlistItems)
  ✓ 105 video disimpan | quota terpakai ~2125 unit

Progress:  89%|████████▊ | 172/194 [15:24<01:30,  4.10s/it]

[173/194] UCZX5B1TcHWJKbwAQuYwEh_w
  ✓ Nadia Ulfah | 735,000 subs
  → 119 video IDs ditemukan (3 page playlistItems)
  ✓ 116 video disimpan | quota terpakai ~2132 unit

Progress:  89%|████████▉ | 173/194 [15:28<01:23,  3.99s/it]

[174/194] UCHgTQpnZJY6nW3X61JbtP2Q
  ✓ dandy's_world creepypastas | 55,000 subs
  → 115 video IDs ditemukan (3 page playlistItems)
  ✓ 43 video disimpan | quota terpakai ~2139 unit

Progress:  90%|████████▉ | 174/194 [15:32<01:20,  4.04s/it]

[175/194] UC2zbpOnhs0PwkHza5mkpDYQ
  ✓ Wursita Movie | 390,000 subs
  → 115 video IDs ditemukan (3 page playlistItems)
  ✓ 71 video disimpan | quota terpakai ~2146 unit

Progress:  90%|█████████ | 175/194 [15:36<01:17,  4.06s/it]

[176/194] UC2hm5rD_IrfYRMfq5YQudgA
  ✓ Haminations | 8,780,000 subs
  → 92 video IDs ditemukan (2 page playlistItems)
  ✓ 88 video disimpan | quota terpakai ~2151 unit

Progress:  91%|█████████ | 176/194 [15:40<01:12,  4.05s/it]

[177/194] UCpZLNDzplh9FDioOX-jnvKA
  ✓ Seon | 202,000 subs
  → 89 video IDs ditemukan (2 page playlistItems)
  ✓ 85 video disimpan | quota terpakai ~2156 unit

Progress:  91%|█████████ | 177/194 [15:43<01:06,  3.90s/it]

[178/194] UC12ClG0_7aPLNdRNNl_4zTA
  ✓ AJTHEBOLD | 5,090,000 subs
  → 111 video IDs ditemukan (3 page playlistItems)
  ✓ 111 video disimpan | quota terpakai ~2163 unit

Progress:  92%|█████████▏| 178/194 [15:48<01:03,  3.94s/it]

[179/194] UCw-WWK1U5Nlds-ydZNCrkcg
  ✓ Llama Arts | 2,580,000 subs
  → 24 video IDs ditemukan (1 page playlistItems)
  ✓ 24 video disimpan | quota terpakai ~2166 unit

Progress:  92%|█████████▏| 179/194 [15:50<00:54,  3.62s/it]

[180/194] UCfEd-og-67AUEGwUhcUuzqw
  ✓ Bunga CH | 95,700 subs
  → 105 video IDs ditemukan (3 page playlistItems)
  ✓ 97 video disimpan | quota terpakai ~2173 unit

Progress:  93%|█████████▎| 180/194 [15:55<00:53,  3.79s/it]

[181/194] UCFNTq9XKHDNy_1-2lL0kqCg
  ✓ Corpse Husband | 7,010,000 subs
  → 13 video IDs ditemukan (1 page playlistItems)
  ✓ 13 video disimpan | quota terpakai ~2176 unit

Progress:  93%|█████████▎| 181/194 [15:57<00:44,  3.41s/it]

[182/194] UCywlrebEcnkJ6m1y9YViWoQ
  ✓ Sedya Isty | 1,290,000 subs
  → 103 video IDs ditemukan (3 page playlistItems)
  ✓ 100 video disimpan | quota terpakai ~2183 unit

Progress:  94%|█████████▍| 182/194 [16:01<00:43,  3.59s/it]

[183/194] UC_6HKUyjbWkU2iZpnvcJdXA
  ✓ Resty Channel | 619,000 subs
  → 94 video IDs ditemukan (2 page playlistItems)
  ✓ 89 video disimpan | quota terpakai ~2188 unit

Progress:  94%|█████████▍| 183/194 [16:06<00:42,  3.91s/it]

[184/194] UCkEKvvUyjcBU4izHBL8Jq4A
  ✓ Animasi horror | 332 subs
  → 93 video IDs ditemukan (2 page playlistItems)
  ✓ 20 video disimpan | quota terpakai ~2193 unit

Progress:  95%|█████████▍| 184/194 [16:10<00:39,  3.94s/it]

[185/194] UCCyocdgwZVcIfnWzwhVEdLA
  ✓ Choco Pies | 85,100 subs
  → 91 video IDs ditemukan (2 page playlistItems)
  ✓ 84 video disimpan | quota terpakai ~2198 unit

Progress:  95%|█████████▌| 185/194 [16:13<00:33,  3.75s/it]

[186/194] UCTCdn0QxSosQGnaAPgFrBcQ
  ✓ This Abelia | 690,000 subs
  → 90 video IDs ditemukan (2 page playlistItems)
  ✓ 79 video disimpan | quota terpakai ~2203 unit

Progress:  96%|█████████▌| 186/194 [16:17<00:30,  3.76s/it]

[187/194] UC5zayj7sRZ_zHSqwMmduI4g
  ✓ Amel Roblox | 1,160 subs
  → 87 video IDs ditemukan (2 page playlistItems)
  ✓ 73 video disimpan | quota terpakai ~2208 unit

Progress:  96%|█████████▋| 187/194 [16:21<00:26,  3.85s/it]

[188/194] UCVlOEP2q7meEoneD5qgeTxw
  ✓ Nala Fitri | 700,000 subs
  → 88 video IDs ditemukan (2 page playlistItems)
  ✓ 83 video disimpan | quota terpakai ~2213 unit

Progress:  97%|█████████▋| 188/194 [16:25<00:23,  3.92s/it]

[189/194] UCIgexLjhSyzvitCywx-m3vw
  ✓ U Chan | 701,000 subs
  → 87 video IDs ditemukan (2 page playlistItems)
  ✓ 71 video disimpan | quota terpakai ~2218 unit

Progress:  97%|█████████▋| 189/194 [16:29<00:19,  3.83s/it]

[190/194] UCfKQqn93rsJjRa8s2DWLrug
  ✓ Cahaya Iskandar | 149,000 subs
  → 83 video IDs ditemukan (2 page playlistItems)
  ✓ 69 video disimpan | quota terpakai ~2223 unit

Progress:  98%|█████████▊| 190/194 [16:32<00:15,  3.80s/it]

[191/194] UCCfaWHyOqKfen_-p0b7L0Xw
  ✓ SCARY ANIMATED STORIES | 3,860 subs
  → 60 video IDs ditemukan (2 page playlistItems)
  ✓ 51 video disimpan | quota terpakai ~2228 unit

Progress:  98%|█████████▊| 191/194 [16:36<00:11,  3.82s/it]

[192/194] UC8rPkG068jFlejCMBDH582w
  ✓ SIE JACK Animation | 348 subs
  → 82 video IDs ditemukan (2 page playlistItems)
  ✓ 82 video disimpan | quota terpakai ~2233 unit

Progress:  99%|█████████▉| 192/194 [16:40<00:07,  3.81s/it]

[193/194] UCSH77L4K8TrBgVOEdmF3zxw
  ✓ Cerita Misteri Animasi | 155,000 subs
  → 82 video IDs ditemukan (2 page playlistItems)
  ✓ 31 video disimpan | quota terpakai ~2238 unit

Progress:  99%|█████████▉| 193/194 [16:44<00:03,  3.84s/it]

[194/194] UCBp-eiOdKwtEDQ88wqb8fmg
  ✓ Jie Tales | 457,000 subs
  → 81 video IDs ditemukan (2 page playlistItems)
  ✓ 51 video disimpan | quota terpakai ~2243 unit

Progress: 100%|██████████| 194/194 [16:48<00:00,  5.20s/it]

=================================================================
MENYIMPAN DATASET
=================================================================
Duplikat video dihapus: 0 baris

✓ File disimpan: /content/dataset_raw_skripsi.csv
  Total baris  : 33,339
  Total kolom  : 14
  Kolom        : ['video_id', 'title', 'description', 'tags', 'published_at', 'duration_seconds', 'view_count', 'like_count', 'comment_count', 'channel_id', 'channel_title', 'channel_subscriber_count', 'channel_total_views', 'channel_video_count']
  Quota terpakai (estimasi): ~2243 / 10,000 unit
  Channel berhasil : 194
  Channel gagal    : 0

--- Preview 5 baris pertama ---

,video_id,title,description,tags,published_at,duration_seconds,view_count,like_count,comment_count,channel_id,channel_title,channel_subscriber_count,channel_total_views,channel_video_count
0,KLNViIu9n1U,Finding Every CAPYBARA in Roblox Find The Capy...,"Today, Johnny finds all of the capybaras in Ro...",Digging to Escape from Roblox Prison...|Playin...,2025-12-31 23:47:51+00:00,1170,131697,1275,114,UCHudxWzwLDAr06TWFmrP7hQ,Johnny and Marty,9980000,1595235224,928
1,Zb_0l50TJHA,Working at a SCARY FOOD TRUCK in Roblox!,We just dropped NEW MERCH! Grab yours before i...,Digging to Escape from Roblox Prison...|Playin...,2025-12-31 22:57:35+00:00,969,292716,3007,391,UCHudxWzwLDAr06TWFmrP7hQ,Johnny and Marty,9980000,1595235224,928
2,ehfhV-NCkSE,Top 5 Avatar,what top 5 do you want next tho?\n------------...,top 5|dog|dogs|top 5 dog|top 5 dogs|dog meme|d...,2025-12-31 22:57:03+00:00,54,48329,3507,215,UCWXcdemE-1OGDhaSAPAw-4w,squewe,2340000,586989476,812
3,C2Rzk_57ibo,Top 10 Scary Cartoon Theories That Will RUIN Y...,Top 10 Scary Cartoon Theories That Will Ruin Y...,10|top 10|most amazing top 10|top 10 scary|dis...,2025-12-31 22:32:01+00:00,627,24811,1169,169,UCe56RtxwepRSyZ-b--SedOw,DangMattSmith,15200000,3597768054,2770
4,UAbjomUmYnI,Do Not Answer The Doorbell Tonight | VHS Analo...,Become a member: https://www.youtube.com/chann...,texting|text story|horror texts|texts|text con...,2025-12-31 22:15:01+00:00,2265,88903,1633,403,UCeI90iCLm4RrNguS4WwNVVQ,Textify,475000,137363365,865

--- Statistik engagement ---
        view_count  like_count  comment_count  duration_seconds
count      33339.0     33339.0        33339.0           33339.0
mean     1157655.0     23042.0          875.0            1329.0
std      3799417.0     91844.0         3013.0            2597.0
min            0.0         0.0            0.0               0.0
25%        34876.0       758.0           41.0             136.0
50%       163784.0      3236.0          178.0             773.0
75%       765560.0     13458.0          656.0            1431.0
max    186642602.0   3829569.0       167056.0           64163.0

--- Distribusi tahun upload ---
published_at
2020     1196
2021     2183
2022     3003
2023     4986
2024     7395
2025    14576
Name: count, dtype: int64

⬇ Download dimulai: dataset_raw_skripsi.csv

Selesai.

In [ ]:
from google.colab import files
files.download('/content/dataset_raw_skripsi.csv')

In [ ]:
# ============================================================
# YOUTUBE DATA COLLECTOR - SKRIPSI
# Klasifikasi Viral Horror/Brainrot Anak (XGBoost vs LightGBM)
# Google Colab Version
# ============================================================
# OUTPUT KOLOM:
#   video_id, title, description, tags, published_at,
#   duration_seconds, view_count, like_count, comment_count,
#   channel_id, channel_title, channel_subscriber_count,
#   channel_total_views, channel_video_count
# TIDAK ada kolom is_viral — akan dihitung di preprocessing
# ============================================================

# STEP 1: Install & Import
!pip install google-api-python-client pandas tqdm --quiet

import pandas as pd
import time
import random
import re
import json
import os
from datetime import datetime, timezone
from tqdm import tqdm
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

# STEP 2: Konfigurasi
API_KEY = "(masukkan API KEY kamu di sini)"   # ← ganti dengan API key kamu
CUTOFF_DATE = datetime(2026, 1, 1, tzinfo=timezone.utc)   # ambil video publishedAt < 2026-01-01
OLDEST_DATE  = datetime(2020, 1, 1, tzinfo=timezone.utc)  # stop pagination jika video sudah terlalu lama
MAX_VIDEOS_PER_CHANNEL = 300
PROGRESS_FILE = "/content/scraping_progress_batch2.json"  # resume jika Colab disconnect

youtube = build("youtube", "v3", developerKey=API_KEY)

# STEP 3: Daftar 38 Channel ID Lama (batch 2)
# Catatan: UCawnfDlDlCLiu1ZTIkygc9w muncul 2x di list asli → sudah dedup jadi 38 unik
CHANNEL_IDS = [
    "UChirEQ8Q5iGOMEW3TPOo5_Q", "UC4_Ssc1v_P5SrrFjbVG821Q", "UCGGwuSrxDFQymf66OdM_-pw",
    "UCvwn9pGVzKmMS6Ssd8R0pog", "UCYPSqQRAl-E7SyIAPz-9GDA", "UClfw7Mx0Vmh4hDAT0STSohw",
    "UC--QxF30QUdNMP4WpTMe6qg", "UCTpb9vZ_xp0_n84lyT-2yqw", "UCjJdTnEzXa40iNhxtLc_0Ng",
    "UCcwu2DFi0B9WbLSoqeVH9NQ", "UCJ9v-fDARn2Vyl1TX9PfVyA", "UCrn4zm6SwhoVgNBMT8J_T4A",
    "UCnzbx11s43-5ncWWwejPVHg", "UC98_dcRWqBOF8tGrvRnaWmQ", "UC63UrA203WWay62-RA37gCA",
    "UCDP_apI00MkhojUlOFb7gGA", "UC4Gumj80pOghE8G7xq4Yxjg", "UC4hGmH5sABOA70D4fGb8qNQ",
    "UCg55rJ27zjuqod4Cv0ENqPQ", "UCawnfDlDlCLiu1ZTIkygc9w", "UCGJ9FqZHdsq1tGSzSyyJpSw",
    "UCcliUkdKk9J_7gdsT3No0Xg", "UCFQoE23adk7NSPNhBlanu4w", "UCwjojsJdcSNP0UT1R-S6mFA",
    "UCR_J_SntqJh5eXw66d5hJxA", "UCFSqAZl3AxxMyaHouB2GKSg", "UCc2RL8jvY1rJPuCnJVsIQWw",
    "UCUwP2XkG17aD53fmvYoA6Yw", "UCfHi2LIb2D4f1hYzX5de0IA", "UCQtoYB7gpftk98WsshIG_fQ",
    "UC7GWXKxiy9_AU9TytEh00eg", "UCqkVT_bXF2rTyjdIxapaHbw", "UCY_vG2Em4Y4zjOJLmVkiQ1g",
    "UCOTQEQd8Rc_Ny30qhz7K5xA", "UC1WSSEbkczMjxJ89TGE58jA", "UCFjaPtpDqdMozLOLbcAo7eg",
    "UCs1vLs4_lXRMVytjQLizNdA", "UCZhUolzN9vMdkjWrnT9DQ2A",
]
print(f"Total channel: {len(CHANNEL_IDS)}")

# STEP 4: Helper — parse durasi ISO 8601 ke detik
def parse_duration(duration_iso):
    match = re.match(r'PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?', duration_iso or "")
    if not match:
        return 0
    h = int(match.group(1) or 0)
    m = int(match.group(2) or 0)
    s = int(match.group(3) or 0)
    return h * 3600 + m * 60 + s

def parse_dt(iso_str):
    """Parse ISO 8601 string ke datetime UTC."""
    if not iso_str:
        return None
    return datetime.fromisoformat(iso_str.replace("Z", "+00:00"))

# STEP 5: Load/save progress (resume-safe)
def load_progress():
    if os.path.exists(PROGRESS_FILE):
        with open(PROGRESS_FILE, "r") as f:
            return json.load(f)
    return {"done_channels": [], "rows": []}

def save_progress(done_channels, rows):
    with open(PROGRESS_FILE, "w") as f:
        json.dump({"done_channels": done_channels, "rows": rows}, f)

# STEP 6: Ambil data channel + uploads playlist ID (1 API call, bukan 2)
def get_channel_info(channel_id):
    """
    1 call: channels().list(part="snippet,statistics,contentDetails")
    Return: dict info channel + playlist_id uploads
    """
    try:
        resp = youtube.channels().list(
            part="snippet,statistics,contentDetails",
            id=channel_id
        ).execute()

        if not resp.get("items"):
            return None

        item = resp["items"][0]
        stats = item.get("statistics", {})
        playlist_id = (
            item.get("contentDetails", {})
                .get("relatedPlaylists", {})
                .get("uploads", None)
        )
        return {
            "channel_id":                 channel_id,
            "channel_title":              item["snippet"]["title"],
            "channel_subscriber_count":   int(stats.get("subscriberCount", 0)),
            "channel_total_views":        int(stats.get("viewCount", 0)),
            "channel_video_count":        int(stats.get("videoCount", 0)),
            "uploads_playlist_id":        playlist_id,
        }
    except HttpError as e:
        print(f"  [ERROR] channels.list {channel_id}: {e}")
        return None

# STEP 7: Ambil video IDs dari uploads playlist
# Stop paginasi jika sudah lewat OLDEST_DATE (hemat quota)
def get_video_ids_from_playlist(playlist_id, max_videos=300):
    """
    Ambil video IDs dari uploads playlist.
    Stop jika: (a) sudah max_videos, atau (b) video sudah lebih tua dari OLDEST_DATE.
    Return: list of (video_id, published_at_str)
    """
    items_out = []
    next_page = None

    while len(items_out) < max_videos:
        try:
            resp = youtube.playlistItems().list(
                part="contentDetails",
                playlistId=playlist_id,
                maxResults=50,
                pageToken=next_page
            ).execute()
        except HttpError as e:
            print(f"  [ERROR] playlistItems.list: {e}")
            break

        page_items = resp.get("items", [])
        if not page_items:
            break

        stop_early = False
        for item in page_items:
            cd = item.get("contentDetails", {})
            vid_id = cd.get("videoId")
            pub_at = cd.get("videoPublishedAt", "")

            # Cek apakah sudah terlalu lama
            dt = parse_dt(pub_at)
            if dt and dt < OLDEST_DATE:
                stop_early = True
                break

            items_out.append((vid_id, pub_at))
            if len(items_out) >= max_videos:
                stop_early = True
                break

        next_page = resp.get("nextPageToken")
        if stop_early or not next_page:
            break

    return items_out

# STEP 8: Ambil detail video batch (max 50 per call)
def get_video_details_batch(video_id_list, channel_info):
    """
    1 call videos().list untuk maks 50 video ID.
    Filter: publishedAt harus < CUTOFF_DATE (2026-01-01).
    Return: list of row dicts.
    """
    if not video_id_list:
        return []
    try:
        resp = youtube.videos().list(
            part="snippet,statistics,contentDetails",
            id=",".join(video_id_list)
        ).execute()
    except HttpError as e:
        print(f"  [ERROR] videos.list: {e}")
        return []

    rows = []
    for item in resp.get("items", []):
        snippet    = item.get("snippet", {})
        stats      = item.get("statistics", {})
        content    = item.get("contentDetails", {})

        pub_at = snippet.get("publishedAt", "")
        dt = parse_dt(pub_at)

        # Filter: hanya video sebelum 2026
        if dt and dt >= CUTOFF_DATE:
            continue

        tags = snippet.get("tags", [])

        rows.append({
            # --- identitas video ---
            "video_id":                   item.get("id", ""),
            "title":                      snippet.get("title", ""),
            "description":                snippet.get("description", ""),
            "tags":                       "|".join(tags),   # pakai | bukan , supaya tidak confuse CSV
            "published_at":               pub_at,
            "duration_seconds":           parse_duration(content.get("duration", "")),

            # --- engagement (raw, belum ada label viral) ---
            "view_count":                 int(stats.get("viewCount", 0)),
            "like_count":                 int(stats.get("likeCount", 0)),
            "comment_count":              int(stats.get("commentCount", 0)),

            # --- info channel (denormalized, biar 1 file cukup) ---
            "channel_id":                 channel_info["channel_id"],
            "channel_title":              channel_info["channel_title"],
            "channel_subscriber_count":   channel_info["channel_subscriber_count"],
            "channel_total_views":        channel_info["channel_total_views"],
            "channel_video_count":        channel_info["channel_video_count"],
        })
    return rows

# STEP 9: EKSEKUSI SCRAPING (dengan resume)
print("=" * 65)
print("SCRAPING 200 CHANNELS — HORROR/BRAINROT ANAK")
print(f"Filter: publishedAt < 2026-01-01  |  max {MAX_VIDEOS_PER_CHANNEL} video/channel")
print("=" * 65)

progress    = load_progress()
done_ids    = set(progress["done_channels"])
all_rows    = progress["rows"]
failed      = []
quota_used  = 0

remaining = [ch for ch in CHANNEL_IDS if ch not in done_ids]
print(f"Sudah selesai sebelumnya : {len(done_ids)} channel")
print(f"Sisa yang akan diproses  : {len(remaining)} channel\n")

for idx, channel_id in enumerate(tqdm(remaining, desc="Progress")):
    print(f"\n[{len(done_ids)+1}/{len(CHANNEL_IDS)}] {channel_id}")

    # --- ambil info channel (1 call) ---
    ch_info = get_channel_info(channel_id)
    quota_used += 1
    if not ch_info or not ch_info.get("uploads_playlist_id"):
        print(f"  ✗ Skip (channel tidak ditemukan atau tidak ada uploads playlist)")
        failed.append(channel_id)
        done_ids.add(channel_id)
        save_progress(list(done_ids), all_rows)
        continue

    print(f"  ✓ {ch_info['channel_title']} | {ch_info['channel_subscriber_count']:,} subs")

    # --- ambil video IDs (N calls playlistItems.list) ---
    vid_pairs = get_video_ids_from_playlist(
        ch_info["uploads_playlist_id"],
        max_videos=MAX_VIDEOS_PER_CHANNEL
    )
    pages_used = (len(vid_pairs) // 50) + 1
    quota_used += pages_used

    vid_ids = [v[0] for v in vid_pairs if v[0]]
    print(f"  → {len(vid_ids)} video IDs ditemukan ({pages_used} page playlistItems)")

    if not vid_ids:
        done_ids.add(channel_id)
        save_progress(list(done_ids), all_rows)
        continue

    # --- ambil detail video (batch 50, N calls videos.list) ---
    channel_rows = []
    for i in range(0, len(vid_ids), 50):
        batch = vid_ids[i:i+50]
        rows  = get_video_details_batch(batch, ch_info)
        channel_rows.extend(rows)
        quota_used += 1
        time.sleep(0.3)

    all_rows.extend(channel_rows)
    done_ids.add(channel_id)
    print(f"  ✓ {len(channel_rows)} video disimpan | quota terpakai ~{quota_used} unit")

    # --- simpan progress setiap channel ---
    save_progress(list(done_ids), all_rows)

    # delay antar channel
    time.sleep(random.uniform(1.0, 2.0))

# STEP 10: Buat DataFrame & simpan CSV
print("\n" + "=" * 65)
print("MENYIMPAN DATASET")
print("=" * 65)

df = pd.DataFrame(all_rows)

# Buang duplikat video_id (kalau channel overlap)
before = len(df)
df = df.drop_duplicates(subset="video_id").reset_index(drop=True)
print(f"Duplikat video dihapus: {before - len(df)} baris")

# Urutkan dari terbaru
df["published_at"] = pd.to_datetime(df["published_at"], utc=True)
df = df.sort_values("published_at", ascending=False).reset_index(drop=True)

OUTPUT_PATH = "/content/dataset_raw_skripsi_batch2.csv"
df.to_csv(OUTPUT_PATH, index=False)

print(f"\n✓ File disimpan: {OUTPUT_PATH}")
print(f"  Total baris  : {len(df):,}")
print(f"  Total kolom  : {len(df.columns)}")
print(f"  Kolom        : {list(df.columns)}")
print(f"  Quota terpakai (estimasi): ~{quota_used} / 10,000 unit")
print(f"  Channel berhasil : {len(done_ids) - len(failed)}")
print(f"  Channel gagal    : {len(failed)}")

# STEP 11: Preview & statistik ringkas
print("\n--- Preview 5 baris pertama ---")
display(df.head())

print("\n--- Statistik engagement ---")
print(df[["view_count","like_count","comment_count","duration_seconds"]].describe().round(0))

print("\n--- Distribusi tahun upload ---")
print(df["published_at"].dt.year.value_counts().sort_index())

# STEP 12: Download
from google.colab import files
files.download(OUTPUT_PATH)
print(f"\n⬇ Download dimulai: dataset_raw_skripsi_batch2.csv")

if failed:
    fail_path = "/content/failed_channels.txt"
    with open(fail_path, "w") as f:
        f.write("\n".join(failed))
    files.download(fail_path)
    print(f"⬇ Download dimulai: failed_channels.txt ({len(failed)} channel gagal)")

print("\nSelesai.")

Total channel: 38
=================================================================
SCRAPING 200 CHANNELS — HORROR/BRAINROT ANAK
Filter: publishedAt < 2026-01-01  |  max 300 video/channel
=================================================================
Sudah selesai sebelumnya : 0 channel
Sisa yang akan diproses  : 38 channel

Progress:   0%|          | 0/38 [00:00<?, ?it/s]

[1/38] UChirEQ8Q5iGOMEW3TPOo5_Q
  ✓ Dunia Budi | 2,200,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 161 video disimpan | quota terpakai ~14 unit

Progress:   3%|▎         | 1/38 [00:05<03:33,  5.78s/it]

[2/38] UC4_Ssc1v_P5SrrFjbVG821Q
  ✓ Adam B | 5,440,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 263 video disimpan | quota terpakai ~28 unit

Progress:   5%|▌         | 2/38 [00:11<03:28,  5.78s/it]

[3/38] UCGGwuSrxDFQymf66OdM_-pw
  ✓ AKUDAV | 7,490,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 157 video disimpan | quota terpakai ~42 unit

Progress:   8%|▊         | 3/38 [00:17<03:28,  5.96s/it]

[4/38] UCvwn9pGVzKmMS6Ssd8R0pog
  ✓ Andreas Eskander | 13,800,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 177 video disimpan | quota terpakai ~56 unit

Progress:  11%|█         | 4/38 [00:23<03:21,  5.92s/it]

[5/38] UCYPSqQRAl-E7SyIAPz-9GDA
  ✓ Arsyla Mahestri Rahayu | 5,600,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 3 video disimpan | quota terpakai ~70 unit

Progress:  13%|█▎        | 5/38 [00:29<03:19,  6.06s/it]

[6/38] UClfw7Mx0Vmh4hDAT0STSohw
  ✓ BANGJBLOX | 5,400,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~84 unit

Progress:  16%|█▌        | 6/38 [00:36<03:19,  6.25s/it]

[7/38] UC--QxF30QUdNMP4WpTMe6qg
  ✓ BanoBarb | 22,200 subs
  → 30 video IDs ditemukan (1 page playlistItems)
  ✓ 14 video disimpan | quota terpakai ~87 unit

Progress:  18%|█▊        | 7/38 [00:38<02:35,  5.01s/it]

[8/38] UCTpb9vZ_xp0_n84lyT-2yqw
  ✓ CatCrafter | 128,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 225 video disimpan | quota terpakai ~101 unit

Progress:  21%|██        | 8/38 [00:44<02:35,  5.17s/it]

[9/38] UCjJdTnEzXa40iNhxtLc_0Ng
  ✓ DIABOLO | 2,690,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 276 video disimpan | quota terpakai ~115 unit

Progress:  24%|██▎       | 9/38 [00:49<02:30,  5.18s/it]

[10/38] UCcwu2DFi0B9WbLSoqeVH9NQ
  ✓ Dinda Family | 2,560,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 218 video disimpan | quota terpakai ~129 unit

Progress:  26%|██▋       | 10/38 [00:55<02:29,  5.33s/it]

[11/38] UCJ9v-fDARn2Vyl1TX9PfVyA
  ✓ Dunia Budi Roblox | 819,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 155 video disimpan | quota terpakai ~143 unit

Progress:  29%|██▉       | 11/38 [01:01<02:27,  5.46s/it]

[12/38] UCrn4zm6SwhoVgNBMT8J_T4A
  ✓ Dunia Dinda | 5,630,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 216 video disimpan | quota terpakai ~157 unit

Progress:  32%|███▏      | 12/38 [01:06<02:22,  5.48s/it]

[13/38] UCnzbx11s43-5ncWWwejPVHg
  ✓ Popo Mimi ROBLOX | 1,700,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 211 video disimpan | quota terpakai ~171 unit

Progress:  34%|███▍      | 13/38 [01:11<02:12,  5.32s/it]

[14/38] UC98_dcRWqBOF8tGrvRnaWmQ
  ✓ Dunia Hara | 5,870,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 265 video disimpan | quota terpakai ~185 unit

Progress:  37%|███▋      | 14/38 [01:17<02:10,  5.43s/it]

[15/38] UC63UrA203WWay62-RA37gCA
  ✓ Dunia Kelvin Sakura | 28,000 subs
  → 178 video IDs ditemukan (4 page playlistItems)
  ✓ 11 video disimpan | quota terpakai ~194 unit

Progress:  39%|███▉      | 15/38 [01:21<01:54,  4.97s/it]

[16/38] UCDP_apI00MkhojUlOFb7gGA
  ✓ el prana | 4,280,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 155 video disimpan | quota terpakai ~208 unit

Progress:  42%|████▏     | 16/38 [01:26<01:54,  5.19s/it]

[17/38] UC4Gumj80pOghE8G7xq4Yxjg
  ✓ FIZIstyle | 12,000,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 175 video disimpan | quota terpakai ~222 unit

Progress:  45%|████▍     | 17/38 [01:32<01:49,  5.23s/it]

[18/38] UC4hGmH5sABOA70D4fGb8qNQ
  ✓ Frost Diamond | 47,500,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~236 unit

Progress:  47%|████▋     | 18/38 [01:39<01:54,  5.75s/it]

[19/38] UCg55rJ27zjuqod4Cv0ENqPQ
  ✓ CERITA CHERYN | 171,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 270 video disimpan | quota terpakai ~250 unit

Progress:  50%|█████     | 19/38 [01:44<01:47,  5.66s/it]

[20/38] UCawnfDlDlCLiu1ZTIkygc9w
  ✓ Gu e Ju | 9,810,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 180 video disimpan | quota terpakai ~264 unit

Progress:  53%|█████▎    | 20/38 [01:50<01:45,  5.84s/it]

[21/38] UCGJ9FqZHdsq1tGSzSyyJpSw
  ✓ Gummo | 2,320 subs
  → 10 video IDs ditemukan (1 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~267 unit

Progress:  55%|█████▌    | 21/38 [01:53<01:22,  4.84s/it]

[22/38] UCcliUkdKk9J_7gdsT3No0Xg
  ✓ HAURAFY | 46,700 subs
  → 252 video IDs ditemukan (6 page playlistItems)
  ✓ 100 video disimpan | quota terpakai ~280 unit

Progress:  58%|█████▊    | 22/38 [01:58<01:17,  4.85s/it]

[23/38] UCFQoE23adk7NSPNhBlanu4w
  ✓ Hirotada Radifan | 4,150,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 237 video disimpan | quota terpakai ~294 unit

Progress:  61%|██████    | 23/38 [02:03<01:15,  5.06s/it]

[24/38] UCwjojsJdcSNP0UT1R-S6mFA
  ✓ Ibnu Zuu | 360,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 217 video disimpan | quota terpakai ~308 unit

Progress:  63%|██████▎   | 24/38 [02:09<01:14,  5.30s/it]

[25/38] UCR_J_SntqJh5eXw66d5hJxA
  ✓ Matthew Beem | 8,100,000 subs
  → 244 video IDs ditemukan (5 page playlistItems)
  ✓ 234 video disimpan | quota terpakai ~319 unit

Progress:  66%|██████▌   | 25/38 [02:13<01:04,  5.00s/it]

[26/38] UCFSqAZl3AxxMyaHouB2GKSg
  ✓ Mikael TubeHD | 14,700,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 209 video disimpan | quota terpakai ~333 unit

Progress:  68%|██████▊   | 26/38 [02:20<01:04,  5.36s/it]

[27/38] UCc2RL8jvY1rJPuCnJVsIQWw
  ✓ MSToons | 1,490,000 subs
  → 219 video IDs ditemukan (5 page playlistItems)
  ✓ 164 video disimpan | quota terpakai ~344 unit

Progress:  71%|███████   | 27/38 [02:24<00:57,  5.20s/it]

[28/38] UCUwP2XkG17aD53fmvYoA6Yw
  ✓ Mugiwara Dlufz | 247,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 227 video disimpan | quota terpakai ~358 unit

Progress:  74%|███████▎  | 28/38 [02:30<00:54,  5.41s/it]

[29/38] UCfHi2LIb2D4f1hYzX5de0IA
  ✓ Najwa Jasmine | 294,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 249 video disimpan | quota terpakai ~372 unit

Progress:  76%|███████▋  | 29/38 [02:36<00:50,  5.62s/it]

[30/38] UCQtoYB7gpftk98WsshIG_fQ
  ✓ Nzmaa | 105,000 subs
  → 286 video IDs ditemukan (6 page playlistItems)
  ✓ 173 video disimpan | quota terpakai ~385 unit

Progress:  79%|███████▉  | 30/38 [02:42<00:45,  5.70s/it]

[31/38] UC7GWXKxiy9_AU9TytEh00eg
  ✓ Rizky Riplay | 14,200,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 198 video disimpan | quota terpakai ~399 unit

Progress:  82%|████████▏ | 31/38 [02:48<00:40,  5.73s/it]

[32/38] UCqkVT_bXF2rTyjdIxapaHbw
  ✓ robsYT | 3,290 subs
  → 9 video IDs ditemukan (1 page playlistItems)
  ✓ 1 video disimpan | quota terpakai ~402 unit

Progress:  84%|████████▍ | 32/38 [02:50<00:27,  4.52s/it]

[33/38] UCY_vG2Em4Y4zjOJLmVkiQ1g
  ✓ Sakujoker | 2,050 subs
  → 30 video IDs ditemukan (1 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~405 unit

Progress:  87%|████████▋ | 33/38 [02:53<00:20,  4.02s/it]

[34/38] UCOTQEQd8Rc_Ny30qhz7K5xA
  ✓ Sakura LF | 58,000 subs
  → 22 video IDs ditemukan (1 page playlistItems)
  ✓ 11 video disimpan | quota terpakai ~408 unit

Progress:  89%|████████▉ | 34/38 [02:55<00:13,  3.48s/it]

[35/38] UC1WSSEbkczMjxJ89TGE58jA
  ✓ SakuraVegeta | 14,200 subs
  → 22 video IDs ditemukan (1 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~411 unit

Progress:  92%|█████████▏| 35/38 [02:57<00:09,  3.04s/it]

[36/38] UCFjaPtpDqdMozLOLbcAo7eg
  ✓ SAKUVEE | 1,630 subs
  → 71 video IDs ditemukan (2 page playlistItems)
  ✓ 0 video disimpan | quota terpakai ~416 unit

Progress:  95%|█████████▍| 36/38 [03:00<00:05,  2.95s/it]

[37/38] UCs1vLs4_lXRMVytjQLizNdA
  ✓ SPONSIX | 1,040,000 subs
  → 286 video IDs ditemukan (6 page playlistItems)
  ✓ 199 video disimpan | quota terpakai ~429 unit

Progress:  97%|█████████▋| 37/38 [03:05<00:03,  3.65s/it]

[38/38] UCZhUolzN9vMdkjWrnT9DQ2A
  ✓ Stromedy | 14,000,000 subs
  → 300 video IDs ditemukan (7 page playlistItems)
  ✓ 273 video disimpan | quota terpakai ~443 unit

Progress: 100%|██████████| 38/38 [03:11<00:00,  5.04s/it]

=================================================================
MENYIMPAN DATASET
=================================================================
Duplikat video dihapus: 0 baris

✓ File disimpan: /content/dataset_raw_skripsi_batch2.csv
  Total baris  : 5,624
  Total kolom  : 14
  Kolom        : ['video_id', 'title', 'description', 'tags', 'published_at', 'duration_seconds', 'view_count', 'like_count', 'comment_count', 'channel_id', 'channel_title', 'channel_subscriber_count', 'channel_total_views', 'channel_video_count']
  Quota terpakai (estimasi): ~443 / 10,000 unit
  Channel berhasil : 38
  Channel gagal    : 0

--- Preview 5 baris pertama ---

,video_id,title,description,tags,published_at,duration_seconds,view_count,like_count,comment_count,channel_id,channel_title,channel_subscriber_count,channel_total_views,channel_video_count
0,n1Q3t5R1B80,Yuta Mio Dan Baby Celine Jadi Kucing Hancurkan...,#roblox #duniabudi,,2025-12-31 23:01:18+00:00,1555,2049354,21853,419,UCJ9v-fDARn2Vyl1TX9PfVyA,Dunia Budi Roblox,819000,460555023,515
1,fHnrSZDHWY8,Yuta Mio Panik CCTV Rekam ANOMALI SUSU MILO KO...,Bantu LIKE SHARE & SUBSCRIBE supaya YUTA SEMAN...,Sakura|Sakura school simulator|Sakura horror s...,2025-12-31 23:01:06+00:00,608,8524,14,2,UC63UrA203WWay62-RA37gCA,Dunia Kelvin Sakura,28000,14941366,178
2,PtRdpfqhuwI,Yuta Mio Pawai Bus Boboiboy BLAZE ICE DURI Di ...,"Sakura School Simulator\nSelamat Menonton ya, ...",,2025-12-31 23:00:43+00:00,1149,734936,2887,68,UChirEQ8Q5iGOMEW3TPOo5_Q,Dunia Budi,2200000,826523720,1548
3,MMV6EWeO3ZQ,Yuta Mio Buat Rumah Pohon Paling Aman Dari PAS...,Yuta Mio Buat Rumah Pohon Paling Aman Dari PAS...,#sakuraschoolsimulatordrama|#idsakura|#sakuras...,2025-12-31 23:00:30+00:00,829,5308288,10200,142,UCs1vLs4_lXRMVytjQLizNdA,SPONSIX,1040000,513219878,286
4,Jz4ZtUtPWg0,The Craziest Things I've Ever Done,Download Brawl Stars and start creating your o...,,2025-12-31 21:47:31+00:00,37,96437,1646,58,UCR_J_SntqJh5eXw66d5hJxA,Matthew Beem,8100000,1492841088,289

--- Statistik engagement ---
        view_count  like_count  comment_count  duration_seconds
count       5624.0      5624.0         5624.0            5624.0
mean     2073888.0     25397.0          733.0             992.0
std      6544096.0     99989.0         2261.0            1579.0
min            0.0         0.0            0.0               0.0
25%       100186.0       722.0           24.0             486.0
50%       596776.0      3825.0          105.0             661.0
75%      1711267.0     15562.0          398.0            1175.0
max    154934440.0   2631792.0        73401.0           42898.0

--- Distribusi tahun upload ---
published_at
2020     130
2021     168
2022      83
2023     396
2024    1029
2025    3818
Name: count, dtype: int64

⬇ Download dimulai: dataset_raw_skripsi_batch2.csv

Selesai.

In [ ]:
# ============================================================
# GABUNGKAN DUA HASIL SCRAPING
# Jalankan di Colab setelah kedua scraping selesai
# ============================================================

import pandas as pd
from google.colab import files

# --- Load dua file CSV ---
# Sesuaikan nama file jika kamu rename salah satunya
df_200 = pd.read_csv("/content/dataset_raw_skripsi.csv")       # hasil 200 channel baru
df_39  = pd.read_csv("/content/dataset_raw_skripsi_batch2.csv")  # hasil 39 channel lama
# Catatan: sebelum run ini, rename dulu salah satu file di Colab
# supaya tidak tertimpa. Klik kanan file di panel Files → Rename.

print(f"Dataset 200 channel : {len(df_200):,} baris")
print(f"Dataset 39 channel  : {len(df_39):,} baris")

# --- Gabungkan ---
df_all = pd.concat([df_200, df_39], ignore_index=True)

# --- Buang duplikat video_id (kalau ada channel overlap antara dua batch) ---
before = len(df_all)
df_all = df_all.drop_duplicates(subset="video_id").reset_index(drop=True)
print(f"Duplikat dihapus    : {before - len(df_all)} baris")

# --- Urutkan dari terbaru ---
df_all["published_at"] = pd.to_datetime(df_all["published_at"], utc=True)
df_all = df_all.sort_values("published_at", ascending=False).reset_index(drop=True)

# --- Simpan ---
OUTPUT = "/content/dataset_gabungan_final.csv"
df_all.to_csv(OUTPUT, index=False)

print(f"\nTotal baris gabungan: {len(df_all):,}")
print(f"Total kolom         : {len(df_all.columns)}")
print(f"Distribusi tahun    :")
print(df_all["published_at"].dt.year.value_counts().sort_index())
print(f"\nDisimpan ke: {OUTPUT}")

# --- Download ---
files.download(OUTPUT)
print("Download dimulai: dataset_gabungan_final.csv")

Dataset 200 channel : 33,339 baris
Dataset 39 channel  : 5,624 baris
Duplikat dihapus    : 0 baris

Total baris gabungan: 38,963
Total kolom         : 14
Distribusi tahun    :
published_at
2020     1326
2021     2351
2022     3086
2023     5382
2024     8424
2025    18394
Name: count, dtype: int64

Disimpan ke: /content/dataset_gabungan_final.csv

Download dimulai: dataset_gabungan_final.csv